import type { Call, Invoice, Lead, Quote, SectorData } from "./types";

/**
 * Cuisiniste. DONNÉES ENTIÈREMENT FICTIVES.
 *
 * Le vocabulaire suit celui de la page secteur (lib/sectors.ts) : devis
 * configurés à 40 paramètres, prospects perdus après le showroom, chantier
 * multi-corps de métier qui déclenche 20 SMS par jour. Géographie lyonnaise,
 * reprise de la première version.
 *
 * Les clés de section sont communes aux trois secteurs, les libellés non :
 * ici `calls` s'appelle « Chantiers » et `leads` « Showroom ». Mêmes formes de
 * données, mots différents.
 */

const quotes: Quote[] = [
  { id: "q01", day: 1,  amount: 18400, reminders: 0, outcome: "pending", category: "cuisine",
    fr: { client: "Famille V. · Écully", project: "Cuisine en L, 14 caissons, plan quartz" },
    en: { client: "V. family · Écully", project: "L-shaped kitchen, 14 units, quartz worktop" } },
  { id: "q02", day: 2,  amount: 24900, reminders: 0, outcome: "pending", category: "cuisine",
    fr: { client: "M. G. · Tassin", project: "Îlot central + électroménager encastré" },
    en: { client: "Mr G. · Tassin", project: "Central island + integrated appliances" } },
  { id: "q03", day: 4,  amount: 7200,  reminders: 3, outcome: "loss", category: "renovation",
    fr: { client: "Mme P. · Villeurbanne", project: "Rénovation façades, plan inchangé" },
    en: { client: "Ms P. · Villeurbanne", project: "Front replacement, layout unchanged" } },
  { id: "q04", day: 5,  amount: 41700, reminders: 1, outcome: "pending", category: "cuisine",
    fr: { client: "SCI B. · Lyon 6e", project: "3 cuisines identiques, programme locatif" },
    en: { client: "SCI B. · Lyon 6e", project: "3 identical kitchens, rental programme" } },
  { id: "q05", day: 7,  amount: 29300, reminders: 1, outcome: "win", category: "cuisine",
    fr: { client: "M. et Mme C. · Charbonnières", project: "Cuisine ouverte + cellier" },
    en: { client: "Mr & Mrs C. · Charbonnières", project: "Open kitchen + pantry" } },
  { id: "q06", day: 9,  amount: 5400,  reminders: 2, outcome: "pending", category: "salle-de-bain",
    fr: { client: "M. Léger · Oullins", project: "Meuble double vasque + colonne miroir" },
    en: { client: "Mr Léger · Oullins", project: "Double vanity unit + mirror column" } },
  { id: "q07", day: 11, amount: 22100, reminders: 1, outcome: "pending", category: "cuisine",
    fr: { client: "Famille Nourrit · Caluire", project: "Cuisine en L, îlot bar, plan céramique" },
    en: { client: "Nourrit family · Caluire", project: "L-shaped kitchen, breakfast island, ceramic top" } },
  { id: "q08", day: 13, amount: 9600,  reminders: 3, outcome: "loss", category: "dressing",
    fr: { client: "Mme Chauvin · Francheville", project: "Dressing d'angle + bibliothèque" },
    en: { client: "Ms Chauvin · Francheville", project: "Corner wardrobe + bookcase" } },
  { id: "q09", day: 15, amount: 16700, reminders: 1, outcome: "win", category: "cuisine",
    fr: { client: "M. Ducret · Craponne", project: "Cuisine en U + plan de travail chêne massif" },
    en: { client: "Mr Ducret · Craponne", project: "U-shaped kitchen + solid oak worktop" } },
  { id: "q10", day: 17, amount: 4100,  reminders: 0, outcome: "pending", category: "salle-de-bain",
    fr: { client: "Mme Roux · Sainte-Foy", project: "Meuble simple vasque + rangement haut" },
    en: { client: "Ms Roux · Sainte-Foy", project: "Single vanity unit + wall storage" } },
  { id: "q11", day: 19, amount: 28300, reminders: 2, outcome: "win", category: "cuisine",
    fr: { client: "M. et Mme Bellard · Limonest", project: "Cuisine ouverte sur séjour, îlot 3 m, cave à vin" },
    en: { client: "Mr & Mrs Bellard · Limonest", project: "Open-plan kitchen, 3 m island, wine cabinet" } },
  { id: "q12", day: 21, amount: 6900,  reminders: 1, outcome: "pending", category: "dressing",
    fr: { client: "M. Vidal · Bron", project: "Dressing chambre parentale, 2,8 m" },
    en: { client: "Mr Vidal · Bron", project: "Master bedroom wardrobe, 2.8 m" } },
  { id: "q13", day: 23, amount: 19200, reminders: 2, outcome: "pending", category: "cuisine",
    fr: { client: "Mme Fournier · Dardilly", project: "Cuisine fermée + verrière atelier" },
    en: { client: "Ms Fournier · Dardilly", project: "Closed kitchen + steel-framed partition" } },
  { id: "q14", day: 25, amount: 8800,  reminders: 3, outcome: "loss", category: "salle-de-bain",
    fr: { client: "M. Grange · Meyzieu", project: "Salle de bain complète, douche à l'italienne" },
    en: { client: "Mr Grange · Meyzieu", project: "Full bathroom, walk-in shower" } },
  { id: "q15", day: 27, amount: 14600, reminders: 1, outcome: "pending", category: "cuisine",
    fr: { client: "Mme Tissot · Rillieux", project: "Cuisine en L, façades mates, hotte plafond" },
    en: { client: "Ms Tissot · Rillieux", project: "L-shaped kitchen, matt fronts, ceiling extractor" } },
  { id: "q16", day: 29, amount: 10300, reminders: 0, outcome: "win", category: "dressing",
    fr: { client: "M. Charrier · Saint-Didier", project: "Dressing + entrée sur mesure" },
    en: { client: "Mr Charrier · Saint-Didier", project: "Wardrobe + bespoke entrance unit" } },
  { id: "q17", day: 30, amount: 12800, reminders: 1, outcome: "win", category: "cuisine",
    fr: { client: "Mme Aubert · Écully", project: "Cuisine linéaire 3,6 m + colonne four" },
    en: { client: "Ms Aubert · Écully", project: "3.6 m galley kitchen + oven tower" } },

  // Au-delà de 30 jours.
  { id: "q18", day: 36, amount: 26400, reminders: 1, outcome: "win", category: "cuisine",
    fr: { client: "M. Payot · Tassin", project: "Cuisine ouverte, îlot avec évier déporté" },
    en: { client: "Mr Payot · Tassin", project: "Open kitchen, island with offset sink" } },
  { id: "q19", day: 45, amount: 7700,  reminders: 2, outcome: "loss", category: "salle-de-bain",
    fr: { client: "Mme Blanc · Villeurbanne", project: "Meuble sur mesure + niche carrelée" },
    en: { client: "Ms Blanc · Villeurbanne", project: "Bespoke unit + tiled niche" } },
  { id: "q20", day: 54, amount: 33800, reminders: 1, outcome: "win", category: "cuisine",
    fr: { client: "M. et Mme Ferrand · Saint-Didier", project: "Cuisine sur mesure, façades noyer, plan pierre" },
    en: { client: "Mr & Mrs Ferrand · Saint-Didier", project: "Bespoke kitchen, walnut fronts, stone worktop" } },
  { id: "q21", day: 63, amount: 11900, reminders: 0, outcome: "win", category: "dressing",
    fr: { client: "Cabinet Marchand · Lyon 6e", project: "Aménagement de bureaux, 6 postes" },
    en: { client: "Marchand practice · Lyon 6e", project: "Office fit-out, 6 workstations" } },
  { id: "q22", day: 72, amount: 21600, reminders: 2, outcome: "win", category: "cuisine",
    fr: { client: "Mme Berthier · Caluire", project: "Cuisine en U + cellier attenant" },
    en: { client: "Ms Berthier · Caluire", project: "U-shaped kitchen + adjoining pantry" } },
  { id: "q23", day: 84, amount: 9100,  reminders: 1, outcome: "win", category: "renovation",
    fr: { client: "M. Rey · Oullins", project: "Remplacement façades + plan stratifié" },
    en: { client: "Mr Rey · Oullins", project: "Front replacement + laminate worktop" } },
];

const calls: Call[] = [
  // Échange repris de la première version : il montre l'agent qui répond depuis
  // le planning réel, sans solliciter le chargé de projet.
  { id: "c01", day: 0, minute: 684, durationSec: 132, urgent: false, outcome: "handled",
    fr: { from: "Famille V. · Écully", summary: "Demande d'avancement à J+12 de la pose. L'agent a répondu avec le jalon en cours et la date de fin prévue, sans solliciter le chargé de projet.",
      transcript: [
        { who: "client", text: "Bonjour, où en est le chantier ? On devait avoir le plan de travail cette semaine." },
        { who: "ia", text: "Bonjour. Les caissons sont posés depuis mardi. Le marbrier est passé prendre le gabarit jeudi." },
        { who: "client", text: "Et la pose du quartz, c'est quand ?" },
        { who: "ia", text: "Sous 8 jours ouvrés après le gabarit, soit au plus tard le 12. L'électricien repasse ensuite pour les raccordements." },
        { who: "client", text: "Parfait, merci." },
        { who: "ia", text: "Je vous envoie une photo à chaque étape. Bonne journée." },
      ],
      action: "Traité · aucune action" },
    en: { from: "V. family · Écully", summary: "Progress request at D+12 of the fit. The agent answered with the current milestone and the expected end date, without involving the project manager.",
      transcript: [
        { who: "client", text: "Hello, where is the job at? We were meant to have the worktop this week." },
        { who: "ia", text: "Hello. The units have been in since Tuesday. The stonemason came for the template on Thursday." },
        { who: "client", text: "And when does the quartz go in?" },
        { who: "ia", text: "Within 8 working days of the template, so the 12th at the latest. The electrician comes back after that for the connections." },
        { who: "client", text: "Perfect, thank you." },
        { who: "ia", text: "I will send you a photo at each stage. Have a good day." },
      ],
      action: "Handled · no action" } },
  { id: "c02", day: 0, minute: 545, durationSec: 198, urgent: true, outcome: "escalated",
    fr: { from: "M. et Mme C. · Charbonnières", summary: "Le plombier signale une arrivée d'eau non conforme au plan. Décalage de pose probable : l'agent n'a pas tranché et a remonté le dossier.",
      transcript: [
        { who: "client", text: "Le plombier dit que l'arrivée d'eau n'est pas là où c'est marqué sur le plan." },
        { who: "ia", text: "Je vérifie… le plan de pose date du 3, la visite technique du 28. L'écart est réel." },
        { who: "client", text: "Ça décale la pose ?" },
        { who: "ia", text: "Probablement, mais c'est une décision de chantier. Je transmets à votre chargé de projet avec les deux plans, il vous rappelle avant midi." },
      ],
      action: "Escaladé · chargé de projet notifié" },
    en: { from: "Mr & Mrs C. · Charbonnières", summary: "The plumber reports a water inlet that does not match the plan. Likely delay: the agent did not decide and escalated instead.",
      transcript: [
        { who: "client", text: "The plumber says the water inlet is not where the plan shows it." },
        { who: "ia", text: "Let me check… the fitting plan is dated the 3rd, the site survey the 28th. The discrepancy is real." },
        { who: "client", text: "Does that push the fit back?" },
        { who: "ia", text: "Probably, but that is a site decision. I am sending both plans to your project manager, they will call you before noon." },
      ],
      action: "Escalated · project manager notified" } },
  { id: "c03", day: 1, minute: 640, durationSec: 84, urgent: false, outcome: "handled",
    fr: { from: "SCI B. · Lyon 6e", summary: "Question sur le délai de livraison des trois cuisines du programme.",
      transcript: [
        { who: "client", text: "Les trois cuisines sont livrées en même temps ou étalées ?" },
        { who: "ia", text: "Livraison groupée prévue semaine 12, pose étalée sur trois semaines pour ne mobiliser qu'une équipe." },
        { who: "client", text: "D'accord, ça me va." },
      ],
      action: "Traité · aucune action" },
    en: { from: "SCI B. · Lyon 6e", summary: "Question on delivery timing for the three kitchens in the programme.",
      transcript: [
        { who: "client", text: "Are the three kitchens delivered together or staggered?" },
        { who: "ia", text: "Grouped delivery in week 12, fitting spread over three weeks so only one team is tied up." },
        { who: "client", text: "Fine, that works for me." },
      ],
      action: "Handled · no action" } },
  { id: "c04", day: 2, minute: 673, durationSec: 143, urgent: false, outcome: "handled",
    fr: { from: "Mme Aubert · Écully", summary: "Le client veut changer la teinte de la crédence avant commande.",
      transcript: [
        { who: "client", text: "On peut encore changer la crédence ? On hésite avec le gris." },
        { who: "ia", text: "La commande part vendredi, donc oui, jusqu'à jeudi soir." },
        { who: "client", text: "D'accord, je vous confirme demain." },
        { who: "ia", text: "Je bloque la ligne et je préviens votre commercial." },
      ],
      action: "Ligne bloquée · commercial prévenu" },
    en: { from: "Ms Aubert · Écully", summary: "Client wants to change the splashback colour before ordering.",
      transcript: [
        { who: "client", text: "Can we still change the splashback? We are torn with the grey." },
        { who: "ia", text: "The order goes out on Friday, so yes — until Thursday evening." },
        { who: "client", text: "Right, I will confirm tomorrow." },
        { who: "ia", text: "I am holding the line item and alerting your salesperson." },
      ],
      action: "Line item held · salesperson alerted" } },
  { id: "c05", day: 4, minute: 498, durationSec: 202, urgent: true, outcome: "escalated",
    fr: { from: "M. G. · Tassin", summary: "Façade laquée livrée rayée, la pose est prévue lundi.",
      transcript: [
        { who: "client", text: "Il y a une rayure de dix centimètres sur la façade du grand meuble." },
        { who: "ia", text: "Sur du laqué, ça ne se reprend pas sur place. C'est un remplacement fournisseur." },
        { who: "ia", text: "Je remonte au chargé de projet pour qu'il lance le litige et décale la pose de ce meuble." },
      ],
      action: "Escaladé · litige fournisseur à ouvrir" },
    en: { from: "Mr G. · Tassin", summary: "Lacquered front delivered scratched, fitting due Monday.",
      transcript: [
        { who: "client", text: "There is a ten-centimetre scratch on the large unit's front." },
        { who: "ia", text: "On lacquer that cannot be touched up on site. It is a supplier replacement." },
        { who: "ia", text: "I am escalating to the project manager to raise the claim and push that unit's fitting back." },
      ],
      action: "Escalated · supplier claim to open" } },
  { id: "c06", day: 6, minute: 560, durationSec: 88, urgent: false, outcome: "handled",
    fr: { from: "Famille Nourrit · Caluire", summary: "Question sur la présence de l'électricien.",
      transcript: [
        { who: "client", text: "L'électricien vient bien mercredi ?" },
        { who: "ia", text: "Oui, mercredi matin, avant la pose du plan de travail." },
      ],
      action: "Répondu depuis le planning" },
    en: { from: "Nourrit family · Caluire", summary: "Question about the electrician's visit.",
      transcript: [
        { who: "client", text: "Is the electrician still coming Wednesday?" },
        { who: "ia", text: "Yes, Wednesday morning, before the worktop goes in." },
      ],
      action: "Answered from the schedule" } },
  { id: "c07", day: 9, minute: 621, durationSec: 117, urgent: false, outcome: "handled",
    fr: { from: "Mme Fournier · Dardilly", summary: "Demande de facture d'acompte pour un dossier bancaire.",
      transcript: [
        { who: "client", text: "La banque me demande la facture d'acompte, vous pouvez me la renvoyer ?" },
        { who: "ia", text: "Je vous la renvoie par mail tout de suite, en PDF." },
      ],
      action: "Facture d'acompte renvoyée par email" },
    en: { from: "Ms Fournier · Dardilly", summary: "Asking for the deposit invoice for a bank file.",
      transcript: [
        { who: "client", text: "The bank wants the deposit invoice — can you resend it?" },
        { who: "ia", text: "Sending it to you by email right now, as a PDF." },
      ],
      action: "Deposit invoice resent by email" } },
  { id: "c08", day: 14, minute: 534, durationSec: 165, urgent: false, outcome: "handled",
    fr: { from: "Mme Tissot · Rillieux", summary: "Le client s'inquiète d'un décalage de deux jours.",
      transcript: [
        { who: "client", text: "On m'a dit que la pose glissait, c'est vrai ?" },
        { who: "ia", text: "Le planning affiche un décalage de deux jours lié au plan de travail. Nouvelle date : le 22." },
        { who: "client", text: "Et le carreleur ?" },
        { who: "ia", text: "Il a été replanifié en conséquence, le 24." },
      ],
      action: "Nouvelles dates confirmées · client informé" },
    en: { from: "Ms Tissot · Rillieux", summary: "Client worried about a two-day slip.",
      transcript: [
        { who: "client", text: "I heard the fitting slipped — is that right?" },
        { who: "ia", text: "The schedule shows a two-day slip on the worktop. New date: the 22nd." },
        { who: "client", text: "And the tiler?" },
        { who: "ia", text: "Rescheduled accordingly, the 24th." },
      ],
      action: "New dates confirmed · client informed" } },
  { id: "c09", day: 20, minute: 587, durationSec: 79, urgent: false, outcome: "handled",
    fr: { from: "M. Charrier · Saint-Didier", summary: "Confirmation de la date de réception.",
      transcript: [
        { who: "client", text: "On signe la réception quand ?" },
        { who: "ia", text: "Réception prévue le 28 à 14h avec votre chargé de projet." },
      ],
      action: "Répondu depuis le planning" },
    en: { from: "Mr Charrier · Saint-Didier", summary: "Confirming the handover date.",
      transcript: [
        { who: "client", text: "When do we sign off?" },
        { who: "ia", text: "Handover set for the 28th at 2pm with your project manager." },
      ],
      action: "Answered from the schedule" } },
  { id: "c10", day: 28, minute: 505, durationSec: 134, urgent: false, outcome: "handled",
    fr: { from: "M. Vidal · Bron", summary: "Réglage de portes coulissantes après pose.",
      transcript: [
        { who: "client", text: "Une porte du dressing frotte un peu en bas." },
        { who: "ia", text: "C'est un réglage de galet, pris en garantie. Je programme un passage." },
      ],
      action: "Passage SAV programmé sous garantie" },
    en: { from: "Mr Vidal · Bron", summary: "Adjusting sliding doors after fitting.",
      transcript: [
        { who: "client", text: "One wardrobe door catches slightly at the bottom." },
        { who: "ia", text: "That is a roller adjustment, covered by the warranty. I am booking a visit." },
      ],
      action: "Warranty visit scheduled" } },
  { id: "c11", day: 41, minute: 641, durationSec: 91, urgent: false, outcome: "handled",
    fr: { from: "M. Payot · Tassin", summary: "Question sur l'entretien des façades noyer.",
      transcript: [
        { who: "client", text: "Comment on entretient le noyer ?" },
        { who: "ia", text: "Chiffon microfibre et produit neutre, jamais d'alcool. Je vous envoie la fiche." },
      ],
      action: "Fiche d'entretien envoyée" },
    en: { from: "Mr Payot · Tassin", summary: "Question about caring for walnut fronts.",
      transcript: [
        { who: "client", text: "How do we care for the walnut?" },
        { who: "ia", text: "Microfibre cloth and a neutral cleaner, never alcohol. I am sending you the care sheet." },
      ],
      action: "Care sheet sent" } },
  { id: "c12", day: 59, minute: 519, durationSec: 156, urgent: false, outcome: "handled",
    fr: { from: "M. et Mme Ferrand · Saint-Didier", summary: "Ajout d'un aménagement de tiroir en cours de fabrication.",
      transcript: [
        { who: "client", text: "On peut encore ajouter un aménagement tiroir ?" },
        { who: "ia", text: "La fabrication est lancée, mais un aménagement intérieur reste possible en pose ultérieure." },
        { who: "client", text: "Ça coûte combien ?" },
        { who: "ia", text: "Je fais chiffrer et votre commercial vous rappelle avec le montant." },
      ],
      action: "Transmis pour chiffrage · avenant à préparer" },
    en: { from: "Mr & Mrs Ferrand · Saint-Didier", summary: "Adding a drawer insert mid-production.",
      transcript: [
        { who: "client", text: "Can we still add a drawer insert?" },
        { who: "ia", text: "Production has started, but an internal fitting can still be added later." },
        { who: "client", text: "How much would that be?" },
        { who: "ia", text: "I am sending it for pricing and your salesperson will call you back with the figure." },
      ],
      action: "Sent for pricing · variation to prepare" } },
];

const leads: Lead[] = [
  // Fiche reprise de la première version.
  { id: "l01", day: 0, score: 88, accepted: true, source: "showroom",
    fr: { name: "A. Ruiz · Sainte-Foy", request: "Cuisine ouverte 16 m², maison en cours d'achat, emménagement prévu dans 4 mois. Repartie avec un plan 3D.",
      verdict: "Projet daté, budget évoqué en showroom, plan déjà réalisé.",
      email: { subject: "Votre plan 3D — cuisine ouverte 16 m²",
        body: "Bonjour,\n\nMerci pour votre visite. Vous trouverez le plan 3D en pièce jointe, dans la configuration qu'on a arrêtée ensemble : îlot déporté et cellier au fond.\n\nUn point à trancher avant le chiffrage définitif : le plan de travail. Le stratifié tient dans votre enveloppe, le quartz la dépasse d'environ 2 200 €.\n\nVous voulez que je chiffre les deux ?" } },
    en: { name: "A. Ruiz · Sainte-Foy", request: "16 m² open kitchen, house purchase under way, moving in 4 months. Left with a 3D plan.",
      verdict: "Dated project, budget discussed in the showroom, plan already drawn.",
      email: { subject: "Your 3D plan — 16 m² open kitchen",
        body: "Hello,\n\nThank you for your visit. You will find the 3D plan attached, in the configuration we settled on together: offset island and pantry at the back.\n\nOne thing to decide before final pricing: the worktop. Laminate fits your envelope, quartz goes about €2,200 over it.\n\nWould you like me to price both?" } } },
  { id: "l02", day: 1, score: 64, accepted: true, source: "showroom",
    fr: { name: "T. Amrani · Dardilly", request: "Remplacement des façades sur caissons existants, pas de modification de plan.",
      verdict: "Besoin clair, mais pas d'échéance et budget non abordé.",
      email: { subject: "Remplacement de façades — votre visite de mardi",
        body: "Bonjour,\n\nPour chiffrer un remplacement de façades sans toucher aux caissons, il me manque deux choses : les dimensions relevées et la marque des caissons d'origine.\n\nSi vous m'envoyez trois photos avec un mètre déplié, je vous fais un chiffrage sous 48 h. Pas besoin de repasser au showroom." } },
    en: { name: "T. Amrani · Dardilly", request: "Replacing fronts on existing carcasses, no layout change.",
      verdict: "Clear need, but no deadline and budget not discussed.",
      email: { subject: "Front replacement — your Tuesday visit",
        body: "Hello,\n\nTo price a front replacement without touching the carcasses, I am missing two things: measured dimensions and the make of the original units.\n\nIf you send me three photos with a tape measure extended, I will price it within 48 hours. No need to come back to the showroom." } } },
  { id: "l03", day: 3, score: 9, accepted: false, source: "showroom",
    fr: { name: "Visite sans coordonnées", request: "Passage de 10 minutes, aucune fiche renseignée, aucun contact laissé.",
      verdict: "Rien d'exploitable, pas de moyen de recontact.",
      rejected: "Écartée automatiquement — comptée dans la fréquentation, exclue du pipeline commercial." },
    en: { name: "Walk-in, no contact details", request: "Ten-minute visit, no form filled in, no contact left.",
      verdict: "Nothing actionable, no way to make contact.",
      rejected: "Discarded automatically — counted in footfall, excluded from the sales pipeline." } },
  { id: "l04", day: 4, score: 81, accepted: true, source: "recommandation",
    fr: { name: "M. G. · Tassin", request: "Cuisine haut de gamme, façades laquées, budget confirmé, adressé par un client.",
      verdict: "Recommandation, budget haut, décision rapide.",
      email: { subject: "Votre projet à Tassin",
        body: "Bonjour,\n\nMerci — être adressé par un client déjà livré nous fait gagner l'étape de la mise en confiance.\n\nSur du laqué, le point à caler tôt est le délai fournisseur : douze semaines en ce moment. Je vous propose un rendez-vous cette semaine." } },
    en: { name: "Mr G. · Tassin", request: "High-end kitchen, lacquered fronts, confirmed budget, referred by a client.",
      verdict: "Referral, high budget, quick decision.",
      email: { subject: "Your project in Tassin",
        body: "Hello,\n\nThank you — a referral from a client we have already delivered saves us the trust-building stage.\n\nWith lacquer, the thing to lock in early is the supplier lead time: twelve weeks at the moment. I suggest a meeting this week." } } },
  { id: "l05", day: 6, score: 58, accepted: true, source: "formulaire",
    fr: { name: "M. Léger · Oullins", request: "Meuble de salle de bain double vasque, cherche à comparer.",
      verdict: "Petit ticket mais projet concret.",
      email: { subject: "Meuble double vasque — proposition",
        body: "Bonjour,\n\nSur un double vasque, ce qui fait la différence à l'usage est la profondeur des tiroirs sous vasque, souvent sacrifiée.\n\nJe vous envoie deux configurations, dont une avec tiroirs pleine profondeur." } },
    en: { name: "Mr Léger · Oullins", request: "Double vanity unit, wants to compare options.",
      verdict: "Small ticket but concrete project.",
      email: { subject: "Double vanity unit — proposal",
        body: "Hello,\n\nOn a double vanity, what makes the difference day to day is the depth of the drawers under the basins, often sacrificed.\n\nI am sending two configurations, one with full-depth drawers." } } },
  { id: "l06", day: 8, score: 19, accepted: false, source: "formulaire",
    fr: { name: "Démarchage · mobilier importé", request: "Proposition de partenariat fournisseur.",
      verdict: "Hors sujet.",
      rejected: "Sollicitation fournisseur, pas une demande client. Écartée sans réponse." },
    en: { name: "Cold outreach · imported furniture", request: "Supplier partnership proposal.",
      verdict: "Off-topic.",
      rejected: "Supplier solicitation, not a customer enquiry. Discarded without reply." } },
  { id: "l07", day: 10, score: 76, accepted: true, source: "showroom",
    fr: { name: "Famille Nourrit · Caluire", request: "Cuisine en L avec îlot bar, construction neuve livrée en juin.",
      verdict: "Échéance connue, plan de l'architecte disponible.",
      email: { subject: "Cuisine en L — implantation sur votre plan",
        body: "Bonjour,\n\nJ'ai repris l'implantation directement sur le plan de l'architecte : l'îlot bar tient, à condition de reculer la colonne four de vingt centimètres.\n\nLe chiffrage joint intègre cette modification." } },
    en: { name: "Nourrit family · Caluire", request: "L-shaped kitchen with breakfast island, new build handed over in June.",
      verdict: "Known deadline, architect's plan available.",
      email: { subject: "L-shaped kitchen — layout on your plan",
        body: "Hello,\n\nI have worked the layout straight onto the architect's plan: the breakfast island fits, provided the oven tower moves back twenty centimetres.\n\nThe attached pricing includes that change." } } },
  { id: "l08", day: 12, score: 41, accepted: true, source: "showroom",
    fr: { name: "Mme Chauvin · Francheville", request: "Dressing d'angle, compare avec deux enseignes de grande distribution.",
      verdict: "Comparaison sur le prix, différenciation à faire.",
      email: { subject: "Dressing d'angle — ce qui change",
        body: "Bonjour,\n\nSur un angle, la différence avec du prêt-à-monter se joue sur le caisson d'angle : sur mesure, il n'y a pas d'espace perdu.\n\nJe vous envoie le comparatif en volume utile plutôt qu'en prix seul." } },
    en: { name: "Ms Chauvin · Francheville", request: "Corner wardrobe, comparing with two large retailers.",
      verdict: "Price-driven comparison, needs differentiation.",
      email: { subject: "Corner wardrobe — what differs",
        body: "Hello,\n\nOn a corner, the difference from flat-pack comes down to the corner carcass: made to measure, there is no dead space.\n\nI am sending the comparison in usable volume rather than price alone." } } },
  { id: "l09", day: 16, score: 33, accepted: false, source: "formulaire",
    fr: { name: "Demande hors zone · Marseille", request: "Cuisine complète à installer dans les Bouches-du-Rhône.",
      verdict: "Hors zone de pose.",
      rejected: "Hors rayon d'intervention des équipes de pose. Réponse envoyée avec orientation." },
    en: { name: "Out-of-area enquiry · Marseille", request: "Full kitchen to install in the Bouches-du-Rhône.",
      verdict: "Outside the fitting area.",
      rejected: "Beyond the fitting teams' range. Reply sent with a redirection." } },
  { id: "l10", day: 18, score: 83, accepted: true, source: "recommandation",
    fr: { name: "M. et Mme Bellard · Limonest", request: "Cuisine ouverte sur séjour avec cave à vin, rénovation complète.",
      verdict: "Budget élevé, projet coordonné avec un architecte.",
      email: { subject: "Cuisine ouverte — coordination architecte",
        body: "Bonjour,\n\nSur une ouverture sur séjour, la cave à vin impose une contrainte de ventilation qu'il vaut mieux traiter avec l'architecte dès maintenant.\n\nJe peux participer à votre prochaine réunion de chantier." } },
    en: { name: "Mr & Mrs Bellard · Limonest", request: "Kitchen opening onto the living room with a wine cabinet, full renovation.",
      verdict: "High budget, coordinated with an architect.",
      email: { subject: "Open kitchen — architect coordination",
        body: "Hello,\n\nWhen opening onto a living room, a wine cabinet brings a ventilation constraint best handled with the architect now.\n\nI can join your next site meeting." } } },
  { id: "l11", day: 22, score: 29, accepted: false, source: "showroom",
    fr: { name: "Visite de repérage", request: "Passage rapide, projet à horizon indéterminé.",
      verdict: "Pas de projet daté.",
      rejected: "Aucune échéance, aucun plan. Inscrit en newsletter, sorti du pipeline commercial." },
    en: { name: "Browsing visit", request: "Quick look, no timeline given.",
      verdict: "No dated project.",
      rejected: "No deadline, no plan. Added to the newsletter, removed from the sales pipeline." } },
  { id: "l12", day: 26, score: 69, accepted: true, source: "formulaire",
    fr: { name: "Mme Tissot · Rillieux", request: "Cuisine en L avec verrière, veut aussi la pose du carrelage.",
      verdict: "Multi-lots, coordination à cadrer.",
      email: { subject: "Cuisine et carrelage — un seul interlocuteur",
        body: "Bonjour,\n\nNous prenons la coordination du carreleur : c'est le point qui fait déraper les plannings quand chacun gère son lot.\n\nLe chiffrage joint sépare les deux postes pour rester lisible." } },
    en: { name: "Ms Tissot · Rillieux", request: "L-shaped kitchen with a glazed partition, also wants the tiling done.",
      verdict: "Multi-trade, coordination to frame.",
      email: { subject: "Kitchen and tiling — one point of contact",
        body: "Hello,\n\nWe take on coordinating the tiler: that is the point where schedules slip when everyone runs their own trade.\n\nThe attached pricing separates the two so it stays readable." } } },
  { id: "l13", day: 37, score: 72, accepted: true, source: "showroom",
    fr: { name: "M. Payot · Tassin", request: "Cuisine ouverte, évier déporté sur l'îlot, projet pour l'automne.",
      verdict: "Projet daté, contrainte technique identifiée.",
      email: { subject: "Évier sur îlot — la contrainte d'évacuation",
        body: "Bonjour,\n\nDéporter l'évier sur l'îlot suppose une évacuation dans la dalle. Si elle n'existe pas, il faut soit une pompe de relevage, soit un léger rehaussement.\n\nJe viens vérifier sur place avant de figer le plan." } },
    en: { name: "Mr Payot · Tassin", request: "Open kitchen, sink offset onto the island, project for the autumn.",
      verdict: "Dated project, technical constraint identified.",
      email: { subject: "Sink on the island — the drainage constraint",
        body: "Hello,\n\nMoving the sink onto the island means drainage through the slab. If there is none, it is either a lifting pump or a slight raised floor.\n\nI will come and check on site before we freeze the plan." } } },
  { id: "l14", day: 52, score: 88, accepted: true, source: "recommandation",
    fr: { name: "M. et Mme Ferrand · Saint-Didier", request: "Cuisine sur mesure façades noyer, plan pierre, sans contrainte de budget.",
      verdict: "Haut de gamme, recommandation, décision prise.",
      email: { subject: "Cuisine sur mesure — noyer et pierre",
        body: "Bonjour,\n\nNoyer et pierre naturelle vieillissent bien ensemble, à condition de choisir une pierre peu poreuse pour le plan de travail.\n\nJe vous propose une sélection en atelier, sur pièces réelles plutôt que sur échantillons." } },
    en: { name: "Mr & Mrs Ferrand · Saint-Didier", request: "Bespoke kitchen, walnut fronts, stone worktop, no budget constraint.",
      verdict: "High end, referral, decision made.",
      email: { subject: "Bespoke kitchen — walnut and stone",
        body: "Hello,\n\nWalnut and natural stone age well together, provided you choose a low-porosity stone for the worktop.\n\nI suggest a selection at the workshop, on real slabs rather than samples." } } },
  { id: "l15", day: 68, score: 64, accepted: true, source: "formulaire",
    fr: { name: "Cabinet Marchand · Lyon 6e", request: "Aménagement de six postes de travail, devis pour une entreprise.",
      verdict: "Client professionnel, facturation société.",
      email: { subject: "Aménagement de bureaux — six postes",
        body: "Bonjour,\n\nPour un aménagement tertiaire, nous fournissons un devis détaillé par poste, exploitable en comptabilité d'entreprise.\n\nJe vous propose un relevé sur site la semaine prochaine." } },
    en: { name: "Marchand practice · Lyon 6e", request: "Fitting out six workstations, quote for a business.",
      verdict: "Trade client, company invoicing.",
      email: { subject: "Office fit-out — six workstations",
        body: "Hello,\n\nFor a commercial fit-out we provide a quote itemised per workstation, suitable for company accounting.\n\nI suggest a site survey next week." } } },
];

const invoices: Invoice[] = [
  { id: "i01", day: 2,  dueIn: 28, amount: 14650, vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0912", client: "M. et Mme C. · acompte" }, en: { ref: "INV-2026-0912", client: "Mr & Mrs C. · deposit" } },
  { id: "i02", day: 6,  dueIn: 24, amount: 6400,  vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0908", client: "Mme Aubert · acompte" }, en: { ref: "INV-2026-0908", client: "Ms Aubert · deposit" } },
  { id: "i03", day: 10, dueIn: 20, amount: 8350,  vatRate: 0.1, paid: false, category: "cuisine",
    fr: { ref: "F-2026-0904", client: "M. Ducret · acompte" }, en: { ref: "INV-2026-0904", client: "Mr Ducret · deposit" } },
  { id: "i04", day: 14, dueIn: 16, amount: 14150, vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0899", client: "M. et Mme Bellard · acompte" }, en: { ref: "INV-2026-0899", client: "Mr & Mrs Bellard · deposit" } },
  { id: "i05", day: 19, dueIn: 11, amount: 5150,  vatRate: 0.2, paid: false, category: "salle-de-bain",
    fr: { ref: "F-2026-0893", client: "Mme Roux" }, en: { ref: "INV-2026-0893", client: "Ms Roux" } },
  { id: "i06", day: 23, dueIn: 7,  amount: 10300, vatRate: 0.2, paid: true,  category: "dressing",
    fr: { ref: "F-2026-0888", client: "M. Charrier" }, en: { ref: "INV-2026-0888", client: "Mr Charrier" } },
  { id: "i07", day: 27, dueIn: -3, amount: 18300, vatRate: 0.1, paid: false, category: "cuisine",
    fr: { ref: "F-2026-0883", client: "SCI B. · Lyon 6e" }, en: { ref: "INV-2026-0883", client: "SCI B. · Lyon 6e" } },
  { id: "i08", day: 35, dueIn: 18, amount: 13200, vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0874", client: "M. Payot · acompte" }, en: { ref: "INV-2026-0874", client: "Mr Payot · deposit" } },
  { id: "i09", day: 44, dueIn: -9, amount: 6800,  vatRate: 0.2, paid: false, category: "salle-de-bain",
    fr: { ref: "F-2026-0865", client: "Mme Blanc" }, en: { ref: "INV-2026-0865", client: "Ms Blanc" } },
  { id: "i10", day: 53, dueIn: 9,  amount: 16900, vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0853", client: "M. et Mme Ferrand · acompte" }, en: { ref: "INV-2026-0853", client: "Mr & Mrs Ferrand · deposit" } },
  { id: "i11", day: 66, dueIn: 14, amount: 11900, vatRate: 0.2, paid: true,  category: "dressing",
    fr: { ref: "F-2026-0841", client: "Cabinet Marchand" }, en: { ref: "INV-2026-0841", client: "Marchand practice" } },
  { id: "i12", day: 79, dueIn: 5,  amount: 10800, vatRate: 0.1, paid: true,  category: "cuisine",
    fr: { ref: "F-2026-0827", client: "Mme Berthier · acompte" }, en: { ref: "INV-2026-0827", client: "Ms Berthier · deposit" } },
];

export const CUISINISTE_DATA: SectorData = {
  company: "Atelier Cuisines Lyon",
  quotes,
  calls,
  leads,
  invoices,
  categories: [
    { key: "cuisine", fr: "Cuisines", en: "Kitchens" },
    { key: "dressing", fr: "Dressings et rangements", en: "Wardrobes & storage" },
    { key: "salle-de-bain", fr: "Salles de bain", en: "Bathrooms" },
    { key: "renovation", fr: "Rénovation partielle", en: "Partial renovation" },
  ],
  sources: [
    { key: "showroom", fr: "Visite showroom", en: "Showroom visit" },
    { key: "formulaire", fr: "Formulaire du site", en: "Website form" },
    { key: "recommandation", fr: "Recommandation", en: "Referral" },
  ],
};
