import type { Call, Invoice, Lead, Quote, SectorData } from "./types";

/**
 * Installateur photovoltaïque. DONNÉES ENTIÈREMENT FICTIVES.
 *
 * Le vocabulaire suit celui de la page secteur (lib/sectors.ts) : volume de
 * leads non qualifiés, éligibilité MaPrimeRénov, Consuel et mise en service,
 * monitoring de production post-pose. Géographie héraultaise, reprise de la
 * première version.
 *
 * Ici `quotes` porte des dossiers d'installation et `calls` la qualification
 * téléphonique : mêmes formes de données que les autres secteurs, autres mots.
 */

const quotes: Quote[] = [
  { id: "q01", day: 1,  amount: 62400, reminders: 0, outcome: "pending", category: "pro",
    fr: { client: "SCI M. · Montpellier", project: "36 kWc, toiture bac acier, local commercial" },
    en: { client: "SCI M. · Montpellier", project: "36 kWp, steel-deck roof, commercial unit" } },
  { id: "q02", day: 2,  amount: 27600, reminders: 1, outcome: "pending", category: "batterie",
    fr: { client: "M. D. · Narbonne", project: "9 kWc + batterie 10 kWh" },
    en: { client: "Mr D. · Narbonne", project: "9 kWp + 10 kWh battery" } },
  { id: "q03", day: 3,  amount: 16800, reminders: 0, outcome: "pending", category: "residentiel",
    fr: { client: "M. R. · Lunel", project: "6 kWc, remplacement onduleur inclus" },
    en: { client: "Mr R. · Lunel", project: "6 kWp, inverter replacement included" } },
  { id: "q04", day: 5,  amount: 14200, reminders: 1, outcome: "win", category: "residentiel",
    fr: { client: "M. et Mme F. · Béziers", project: "6 kWc, toiture tuiles, revente surplus" },
    en: { client: "Mr & Mrs F. · Béziers", project: "6 kWp, tiled roof, surplus export" } },
  { id: "q05", day: 7,  amount: 8900,  reminders: 3, outcome: "loss", category: "residentiel",
    fr: { client: "Mme A. · Sète", project: "3 kWc autoconsommation totale" },
    en: { client: "Ms A. · Sète", project: "3 kWp full self-consumption" } },
  { id: "q06", day: 9,  amount: 21400, reminders: 1, outcome: "win", category: "residentiel",
    fr: { client: "H. Delcourt · Agde", project: "9 kWc, toiture sud 42 m²" },
    en: { client: "H. Delcourt · Agde", project: "9 kWp, 42 m² south-facing roof" } },
  { id: "q07", day: 11, amount: 34700, reminders: 0, outcome: "pending", category: "pro",
    fr: { client: "Domaine viticole L. · Pézenas", project: "24 kWc sur hangar agricole" },
    en: { client: "L. wine estate · Pézenas", project: "24 kWp on a farm shed" } },
  { id: "q08", day: 13, amount: 19300, reminders: 2, outcome: "pending", category: "batterie",
    fr: { client: "S. Boulanger · Frontignan", project: "7 kWc est-ouest + batterie 5 kWh" },
    en: { client: "S. Boulanger · Frontignan", project: "7 kWp east-west + 5 kWh battery" } },
  { id: "q09", day: 15, amount: 12600, reminders: 1, outcome: "win", category: "residentiel",
    fr: { client: "Mme Cazals · Mèze", project: "5 kWc, toiture tuiles canal" },
    en: { client: "Ms Cazals · Mèze", project: "5 kWp, barrel-tile roof" } },
  { id: "q10", day: 17, amount: 4800,  reminders: 0, outcome: "pending", category: "sav",
    fr: { client: "M. Vernet · Balaruc", project: "Remplacement onduleur hors garantie" },
    en: { client: "Mr Vernet · Balaruc", project: "Out-of-warranty inverter replacement" } },
  { id: "q11", day: 19, amount: 28900, reminders: 2, outcome: "pending", category: "residentiel",
    fr: { client: "M. et Mme Roussel · Clermont-l'Hérault", project: "12 kWc, toiture double pan" },
    en: { client: "Mr & Mrs Roussel · Clermont-l'Hérault", project: "12 kWp, dual-pitch roof" } },
  { id: "q12", day: 21, amount: 9700,  reminders: 3, outcome: "loss", category: "residentiel",
    fr: { client: "M. Salles · Gigean", project: "4 kWc, toiture partiellement ombragée" },
    en: { client: "Mr Salles · Gigean", project: "4 kWp, partly shaded roof" } },
  { id: "q13", day: 23, amount: 18500, reminders: 1, outcome: "win", category: "residentiel",
    fr: { client: "Mme Portal · Villeneuve-lès-Maguelone", project: "8 kWc + gestionnaire d'énergie" },
    en: { client: "Ms Portal · Villeneuve-lès-Maguelone", project: "8 kWp + energy manager" } },
  { id: "q14", day: 25, amount: 51200, reminders: 0, outcome: "pending", category: "pro",
    fr: { client: "Garage Aubin · Lattes", project: "30 kWc + ombrières de parking" },
    en: { client: "Aubin garage · Lattes", project: "30 kWp + car-park canopies" } },
  { id: "q15", day: 27, amount: 6200,  reminders: 1, outcome: "pending", category: "sav",
    fr: { client: "Mme Andrieu · Sète", project: "Nettoyage et contrôle annuel, 3 sites" },
    en: { client: "Ms Andrieu · Sète", project: "Annual clean and inspection, 3 sites" } },
  { id: "q16", day: 29, amount: 23800, reminders: 2, outcome: "win", category: "batterie",
    fr: { client: "M. Fabre · Poussan", project: "10 kWc + batterie 8 kWh, autoconsommation" },
    en: { client: "Mr Fabre · Poussan", project: "10 kWp + 8 kWh battery, self-consumption" } },

  // Au-delà de 30 jours.
  { id: "q17", day: 37, amount: 44600, reminders: 1, outcome: "win", category: "pro",
    fr: { client: "Coopérative agricole · Marsillargues", project: "28 kWc sur bâtiment de stockage" },
    en: { client: "Farmers' cooperative · Marsillargues", project: "28 kWp on a storage building" } },
  { id: "q18", day: 46, amount: 11400, reminders: 3, outcome: "loss", category: "residentiel",
    fr: { client: "M. Teissier · Vias", project: "5 kWc, copropriété horizontale" },
    en: { client: "Mr Teissier · Vias", project: "5 kWp, horizontal condominium" } },
  { id: "q19", day: 55, amount: 32100, reminders: 1, outcome: "win", category: "batterie",
    fr: { client: "M. et Mme Brun · Castelnau-le-Lez", project: "14 kWc + batterie 15 kWh" },
    en: { client: "Mr & Mrs Brun · Castelnau-le-Lez", project: "14 kWp + 15 kWh battery" } },
  { id: "q20", day: 64, amount: 17900, reminders: 0, outcome: "win", category: "residentiel",
    fr: { client: "Mme Granier · Bouzigues", project: "7 kWc, intégration au bâti" },
    en: { client: "Ms Granier · Bouzigues", project: "7 kWp, in-roof integration" } },
  { id: "q21", day: 73, amount: 58300, reminders: 2, outcome: "win", category: "pro",
    fr: { client: "Logistique Sud · Vendargues", project: "40 kWc, toiture entrepôt" },
    en: { client: "Logistique Sud · Vendargues", project: "40 kWp, warehouse roof" } },
  { id: "q22", day: 85, amount: 5400,  reminders: 1, outcome: "win", category: "sav",
    fr: { client: "M. Lacombe · Frontignan", project: "Reprise de câblage + remise en service" },
    en: { client: "Mr Lacombe · Frontignan", project: "Cabling rework + recommissioning" } },
];

const calls: Call[] = [
  // Transcription reprise de la première version : elle montre l'agent qui
  // collecte les six paramètres d'éligibilité avant de passer la main.
  { id: "c01", day: 0, minute: 638, durationSec: 164, urgent: false, outcome: "handled",
    fr: { from: "06 •• •• 27 15", summary: "Maison individuelle, toiture sud sans masque, propriétaire occupant. L'agent a collecté les six paramètres d'éligibilité avant de passer la main.",
      transcript: [
        { who: "ia", text: "Bonjour, vous avez fait une simulation sur notre site. Je vous appelle pour cadrer le projet, ça prend deux minutes." },
        { who: "client", text: "Oui, allez-y." },
        { who: "ia", text: "Vous êtes propriétaire du logement, et il a plus de deux ans ?" },
        { who: "client", text: "Propriétaire, oui. La maison date de 2011." },
        { who: "ia", text: "Votre toiture est orientée comment, et y a-t-il un arbre ou un bâtiment qui fait de l'ombre ?" },
        { who: "client", text: "Plein sud, et rien devant, c'est dégagé." },
        { who: "ia", text: "Dernière question, votre facture d'électricité annuelle est plutôt autour de combien ?" },
        { who: "client", text: "Dans les 2 400 € l'an dernier." },
        { who: "ia", text: "Parfait, votre dossier est complet. Un conseiller vous rappelle avec le reste à charge après aides. Bonne journée." },
      ],
      action: "Qualifié · étude à produire" },
    en: { from: "06 •• •• 27 15", summary: "Detached house, unshaded south-facing roof, owner-occupier. The agent collected the six eligibility parameters before handing over.",
      transcript: [
        { who: "ia", text: "Hello, you ran a simulation on our site. I am calling to frame the project, it takes two minutes." },
        { who: "client", text: "Yes, go ahead." },
        { who: "ia", text: "Do you own the property, and is it more than two years old?" },
        { who: "client", text: "Owner, yes. The house dates from 2011." },
        { who: "ia", text: "Which way does your roof face, and is there a tree or building casting shade?" },
        { who: "client", text: "Due south, and nothing in front, it is clear." },
        { who: "ia", text: "Last question — roughly what is your annual electricity bill?" },
        { who: "client", text: "Around €2,400 last year." },
        { who: "ia", text: "Your file is complete. An adviser will call you back with the net cost after grants. Have a good day." },
      ],
      action: "Qualified · study to produce" } },
  { id: "c02", day: 0, minute: 552, durationSec: 211, urgent: true, outcome: "escalated",
    fr: { from: "04 •• •• 61 09", summary: "Installation posée il y a 14 mois, production en baisse de 31 % sur trois semaines. L'alerte de monitoring avait précédé l'appel du client.",
      transcript: [
        { who: "client", text: "J'ai l'impression que ça produit moins qu'avant, je me trompe ?" },
        { who: "ia", text: "Non, vous avez raison. On a une alerte sur votre installation depuis le 28, la production est 31 % sous la référence saisonnière." },
        { who: "client", text: "Ah. C'est grave ?" },
        { who: "ia", text: "Le profil ressemble à une chaîne déconnectée, pas à un onduleur en panne. Un technicien doit monter voir." },
        { who: "client", text: "Vous pouvez venir quand ?" },
        { who: "ia", text: "Je passe le dossier au SAV, vous êtes sous garantie. Ils vous proposent un créneau aujourd'hui." },
      ],
      action: "SAV sous garantie · escaladé" },
    en: { from: "04 •• •• 61 09", summary: "Installed 14 months ago, output down 31 % over three weeks. The monitoring alert came before the client's call.",
      transcript: [
        { who: "client", text: "I get the feeling it is producing less than before — am I wrong?" },
        { who: "ia", text: "No, you are right. We have had an alert on your system since the 28th, output is 31 % below the seasonal reference." },
        { who: "client", text: "Is that serious?" },
        { who: "ia", text: "The pattern looks like a disconnected string, not a failed inverter. A technician needs to go up and look." },
        { who: "client", text: "When can you come?" },
        { who: "ia", text: "I am passing the file to service, you are under warranty. They will offer you a slot today." },
      ],
      action: "Warranty service · escalated" } },
  { id: "c03", day: 1, minute: 922, durationSec: 128, urgent: false, outcome: "handled",
    fr: { from: "07 •• •• 84 30", summary: "Locataire d'un appartement en copropriété. L'agent a expliqué pourquoi le projet n'est pas réalisable en l'état.",
      transcript: [
        { who: "client", text: "Je voudrais des panneaux, j'habite au dernier étage." },
        { who: "ia", text: "Vous êtes propriétaire ou locataire ?" },
        { who: "client", text: "Locataire." },
        { who: "ia", text: "Dans ce cas la toiture appartient à la copropriété, l'installation passe par un vote en assemblée générale. Ce n'est pas quelque chose qu'on peut engager avec vous seul." },
        { who: "client", text: "D'accord, je comprends." },
        { who: "ia", text: "Je vous envoie par SMS la marche à suivre pour le porter en AG, si vous voulez tenter." },
      ],
      action: "Non éligible · sorti du pipeline" },
    en: { from: "07 •• •• 84 30", summary: "Tenant in a block of flats. The agent explained why the project cannot go ahead as things stand.",
      transcript: [
        { who: "client", text: "I would like panels, I live on the top floor." },
        { who: "ia", text: "Do you own the flat or rent it?" },
        { who: "client", text: "I rent." },
        { who: "ia", text: "Then the roof belongs to the building's owners' association, and an installation requires a vote at a general meeting. That is not something we can commit to with you alone." },
        { who: "client", text: "Right, I understand." },
        { who: "ia", text: "I am texting you how to put it to the meeting, if you want to try." },
      ],
      action: "Not eligible · removed from pipeline" } },
  { id: "c04", day: 2, minute: 601, durationSec: 143, urgent: false, outcome: "handled",
    fr: { from: "06 •• •• 33 47", summary: "Question sur le délai de raccordement après pose.",
      transcript: [
        { who: "client", text: "La pose est faite, c'est quand la mise en service ?" },
        { who: "ia", text: "Le Consuel est passé le 12, la demande de raccordement est déposée. Comptez trois à six semaines côté gestionnaire de réseau." },
        { who: "client", text: "Et je peux produire en attendant ?" },
        { who: "ia", text: "Pas avant la mise en service. Je vous préviens dès que la date tombe." },
      ],
      action: "Répondu depuis le suivi de dossier" },
    en: { from: "06 •• •• 33 47", summary: "Question about grid connection lead time after installation.",
      transcript: [
        { who: "client", text: "The install is done — when does it go live?" },
        { who: "ia", text: "The compliance inspection passed on the 12th, the connection request is filed. Allow three to six weeks with the network operator." },
        { who: "client", text: "Can I generate in the meantime?" },
        { who: "ia", text: "Not before commissioning. I will let you know as soon as the date comes through." },
      ],
      action: "Answered from the case tracker" } },
  { id: "c05", day: 4, minute: 578, durationSec: 96, urgent: false, outcome: "handled",
    fr: { from: "06 •• •• 12 88", summary: "Demande d'attestation pour la déclaration de revenus.",
      transcript: [
        { who: "client", text: "Il me faut l'attestation pour les impôts." },
        { who: "ia", text: "Je vous l'envoie par mail, elle est générée automatiquement à la mise en service." },
      ],
      action: "Attestation envoyée par email" },
    en: { from: "06 •• •• 12 88", summary: "Request for the tax certificate.",
      transcript: [
        { who: "client", text: "I need the certificate for my tax return." },
        { who: "ia", text: "Sending it by email — it is generated automatically at commissioning." },
      ],
      action: "Certificate sent by email" } },
  { id: "c06", day: 6, minute: 634, durationSec: 187, urgent: false, outcome: "handled",
    fr: { from: "04 •• •• 55 21", summary: "Exploitation agricole, projet sur hangar, question sur l'amortissement.",
      transcript: [
        { who: "client", text: "Sur un hangar agricole, ça s'amortit en combien de temps ?" },
        { who: "ia", text: "Cela dépend de votre part d'autoconsommation. Vous consommez surtout en journée ?" },
        { who: "client", text: "Oui, les chambres froides tournent toute la journée." },
        { who: "ia", text: "Alors le profil est favorable. Je transmets à un conseiller pour une étude chiffrée avec vos relevés." },
      ],
      action: "Qualifié · étude agricole à produire" },
    en: { from: "04 •• •• 55 21", summary: "Farm business, project on a shed, question about payback.",
      transcript: [
        { who: "client", text: "On a farm shed, what is the payback period?" },
        { who: "ia", text: "That depends on how much you self-consume. Do you mostly use power during the day?" },
        { who: "client", text: "Yes, the cold rooms run all day." },
        { who: "ia", text: "Then the profile is favourable. I am passing this to an adviser for a costed study using your meter readings." },
      ],
      action: "Qualified · farm study to produce" } },
  { id: "c07", day: 9, minute: 509, durationSec: 174, urgent: true, outcome: "escalated",
    fr: { from: "06 •• •• 70 04", summary: "Onduleur en défaut affiché, plus aucune production depuis la veille.",
      transcript: [
        { who: "client", text: "L'écran affiche un code erreur et il n'y a plus rien qui produit." },
        { who: "ia", text: "Le monitoring confirme : production à zéro depuis hier 14h. Pouvez-vous me lire le code ?" },
        { who: "client", text: "Erreur 0x12." },
        { who: "ia", text: "Défaut d'isolement. C'est un déplacement, pas un redémarrage à distance. Je passe en SAV prioritaire." },
      ],
      action: "Escaladé au SAV · défaut d'isolement" },
    en: { from: "06 •• •• 70 04", summary: "Inverter showing a fault, no output since yesterday.",
      transcript: [
        { who: "client", text: "The screen shows an error code and nothing is generating any more." },
        { who: "ia", text: "Monitoring confirms it: output at zero since 2pm yesterday. Can you read me the code?" },
        { who: "client", text: "Error 0x12." },
        { who: "ia", text: "Insulation fault. That needs a visit, not a remote restart. I am escalating as a priority." },
      ],
      action: "Escalated to service · insulation fault" } },
  { id: "c08", day: 12, minute: 662, durationSec: 118, urgent: false, outcome: "handled",
    fr: { from: "07 •• •• 41 63", summary: "Simulation faite, veut savoir si la toiture fibrociment est compatible.",
      transcript: [
        { who: "client", text: "Ma toiture est en fibrociment, c'est possible ?" },
        { who: "ia", text: "Si elle contient de l'amiante, la pose est exclue sans désamiantage préalable. Vous connaissez l'année de pose ?" },
        { who: "client", text: "Années 80 je crois." },
        { who: "ia", text: "Alors un diagnostic amiante est nécessaire avant toute étude. Je vous envoie la marche à suivre." },
      ],
      action: "En attente diagnostic · non qualifié en l'état" },
    en: { from: "07 •• •• 41 63", summary: "Ran a simulation, wants to know whether a fibre-cement roof works.",
      transcript: [
        { who: "client", text: "My roof is fibre cement — is that possible?" },
        { who: "ia", text: "If it contains asbestos, installation is ruled out without removal first. Do you know the year it was laid?" },
        { who: "client", text: "The eighties, I think." },
        { who: "ia", text: "Then an asbestos survey is required before any study. I am sending you the steps." },
      ],
      action: "Awaiting survey · not qualified as things stand" } },
  { id: "c09", day: 16, minute: 545, durationSec: 89, urgent: false, outcome: "handled",
    fr: { from: "06 •• •• 96 27", summary: "Suivi de production via l'application.",
      transcript: [
        { who: "client", text: "Je n'arrive plus à me connecter à l'appli de suivi." },
        { who: "ia", text: "Je vous renvoie un lien de réinitialisation. Votre installation produit normalement, aucune alerte." },
      ],
      action: "Lien de réinitialisation envoyé" },
    en: { from: "06 •• •• 96 27", summary: "Monitoring app access.",
      transcript: [
        { who: "client", text: "I cannot log into the monitoring app any more." },
        { who: "ia", text: "I am sending you a reset link. Your system is generating normally, no alerts." },
      ],
      action: "Reset link sent" } },
  { id: "c10", day: 22, minute: 592, durationSec: 156, urgent: false, outcome: "handled",
    fr: { from: "04 •• •• 08 74", summary: "Ombrières de parking pour un garage, question sur l'autorisation d'urbanisme.",
      transcript: [
        { who: "client", text: "Pour des ombrières sur le parking, il faut un permis ?" },
        { who: "ia", text: "Au-delà de 20 m², oui, une déclaration préalable au minimum, parfois un permis selon la zone." },
        { who: "client", text: "Vous vous en occupez ?" },
        { who: "ia", text: "Nous préparons et déposons le dossier. Je transmets à un conseiller pour l'étude." },
      ],
      action: "Qualifié · étude ombrières à produire" },
    en: { from: "04 •• •• 08 74", summary: "Car-park canopies for a garage, planning permission question.",
      transcript: [
        { who: "client", text: "For canopies over the car park, do we need permission?" },
        { who: "ia", text: "Above 20 m², yes — a prior notice at minimum, sometimes full permission depending on the zone." },
        { who: "client", text: "Do you handle that?" },
        { who: "ia", text: "We prepare and file the application. I am passing this to an adviser for the study." },
      ],
      action: "Qualified · canopy study to produce" } },
  { id: "c11", day: 31, minute: 517, durationSec: 102, urgent: false, outcome: "handled",
    fr: { from: "06 •• •• 29 55", summary: "Question sur le nettoyage des panneaux.",
      transcript: [
        { who: "client", text: "Il faut nettoyer les panneaux tous les combien ?" },
        { who: "ia", text: "Une fois par an suffit dans la région, sauf proximité d'une exploitation agricole ou d'un axe poussiéreux." },
      ],
      action: "Réponse donnée · contrat d'entretien proposé" },
    en: { from: "06 •• •• 29 55", summary: "Question about cleaning the panels.",
      transcript: [
        { who: "client", text: "How often do the panels need cleaning?" },
        { who: "ia", text: "Once a year is enough in this region, unless you are near a farm or a dusty road." },
      ],
      action: "Answered · maintenance contract offered" } },
  { id: "c12", day: 48, minute: 626, durationSec: 133, urgent: false, outcome: "handled",
    fr: { from: "07 •• •• 63 18", summary: "Ajout d'une batterie sur une installation existante.",
      transcript: [
        { who: "client", text: "J'ai 9 kWc posés chez vous il y a deux ans, je peux ajouter une batterie ?" },
        { who: "ia", text: "Oui, votre onduleur est compatible batterie. Je vérifie le modèle… c'est bien le cas." },
        { who: "client", text: "Ça change quoi sur ma facture ?" },
        { who: "ia", text: "Un conseiller vous rappelle avec la simulation, ça dépend de votre profil de consommation du soir." },
      ],
      action: "Qualifié · étude batterie à produire" },
    en: { from: "07 •• •• 63 18", summary: "Adding a battery to an existing system.",
      transcript: [
        { who: "client", text: "I had 9 kWp fitted by you two years ago — can I add a battery?" },
        { who: "ia", text: "Yes, your inverter is battery-ready. Let me check the model… it is." },
        { who: "client", text: "What does that change on my bill?" },
        { who: "ia", text: "An adviser will call you with the simulation — it depends on your evening consumption profile." },
      ],
      action: "Qualified · battery study to produce" } },
];

const leads: Lead[] = [
  // Fiches reprises de la première version.
  { id: "l01", day: 0, score: 94, accepted: true, source: "simulateur",
    fr: { name: "H. Delcourt · Agde", request: "Maison de 2004, toiture sud 42 m², facture annuelle 2 900 €, propriétaire occupant, projet sous 3 mois.",
      verdict: "Six paramètres d'éligibilité réunis, aides calculées, échéance donnée.",
      email: { subject: "Votre étude — 9 kWc à Agde",
        body: "Bonjour,\n\nVoici l'étude pour votre toiture sud de 42 m². En 9 kWc, la production estimée couvre environ 68 % de votre consommation actuelle.\n\nLe montant est de 21 400 € TTC. Après la prime à l'autoconsommation et la TVA réduite, le reste à charge ressort à 17 900 €.\n\nJe vous propose une visite technique pour valider la structure de charpente avant de figer le devis. Quel jour vous convient ?" } },
    en: { name: "H. Delcourt · Agde", request: "House built 2004, 42 m² south roof, €2,900 annual bill, owner-occupier, project within 3 months.",
      verdict: "All six eligibility parameters met, grants calculated, deadline given.",
      email: { subject: "Your study — 9 kWp in Agde",
        body: "Hello,\n\nHere is the study for your 42 m² south-facing roof. At 9 kWp, estimated output covers around 68 % of your current consumption.\n\nThe amount is €21,400 including VAT. After the self-consumption grant and reduced VAT, the net cost comes to €17,900.\n\nI suggest a technical visit to check the roof structure before we freeze the quote. Which day suits you?" } } },
  { id: "l02", day: 1, score: 71, accepted: true, source: "simulateur",
    fr: { name: "S. Boulanger · Frontignan", request: "Maison de 1978, toiture est-ouest, souhaite une batterie, pas de date arrêtée.",
      verdict: "Éligible, mais orientation moins favorable et projet non daté.",
      email: { subject: "Votre projet solaire à Frontignan",
        body: "Bonjour,\n\nUne toiture est-ouest reste tout à fait exploitable : la production est plus étalée sur la journée, ce qui va plutôt bien avec une batterie.\n\nAvant de chiffrer, il me faut deux informations : votre consommation annuelle en kWh, et l'année de réfection de la toiture si elle a été refaite.\n\nAvec ça je vous envoie une étude chiffrée sous 48 h." } },
    en: { name: "S. Boulanger · Frontignan", request: "House built 1978, east-west roof, wants a battery, no fixed date.",
      verdict: "Eligible, but less favourable orientation and no dated project.",
      email: { subject: "Your solar project in Frontignan",
        body: "Hello,\n\nAn east-west roof is perfectly workable: output is spread more evenly through the day, which suits a battery well.\n\nBefore pricing I need two things: your annual consumption in kWh, and the year the roof was redone if it has been.\n\nWith those I will send you a costed study within 48 hours." } } },
  { id: "l03", day: 2, score: 14, accepted: false, source: "simulateur",
    fr: { name: "Simulation incomplète", request: "Formulaire abandonné à la deuxième étape, code postal seul renseigné.",
      verdict: "Aucun paramètre d'éligibilité, pas de coordonnées vérifiables.",
      rejected: "Écarté automatiquement — aucun commercial mobilisé, relance légère à J+2 pour compléter la simulation." },
    en: { name: "Incomplete simulation", request: "Form abandoned at step two, postcode only.",
      verdict: "No eligibility parameters, no verifiable contact details.",
      rejected: "Discarded automatically — no salesperson involved, light follow-up at D+2 to complete the simulation." } },
  { id: "l04", day: 3, score: 12, accepted: false, source: "simulateur",
    fr: { name: "Locataire · Montpellier centre", request: "Appartement en copropriété, dernier étage.",
      verdict: "Non éligible sans vote de copropriété.",
      rejected: "La toiture appartient à la copropriété. Marche à suivre envoyée par SMS, dossier sorti du pipeline." },
    en: { name: "Tenant · central Montpellier", request: "Flat in a block, top floor.",
      verdict: "Not eligible without an owners' vote.",
      rejected: "The roof belongs to the owners' association. Steps sent by text, file removed from the pipeline." } },
  { id: "l05", day: 5, score: 88, accepted: true, source: "recommandation",
    fr: { name: "Domaine viticole L. · Pézenas", request: "Hangar agricole 400 m², chambres froides en journée, projet 24 kWc.",
      verdict: "Profil d'autoconsommation très favorable, client professionnel.",
      email: { subject: "Hangar agricole — étude 24 kWc",
        body: "Bonjour,\n\nVos chambres froides tournant en journée, votre part d'autoconsommation devrait dépasser 70 % : c'est le cas de figure où l'amortissement est le plus rapide.\n\nL'étude jointe s'appuie sur vos relevés de consommation. Je peux passer valider la charpente du hangar la semaine prochaine." } },
    en: { name: "L. wine estate · Pézenas", request: "400 m² farm shed, cold rooms running in the daytime, 24 kWp project.",
      verdict: "Very favourable self-consumption profile, trade client.",
      email: { subject: "Farm shed — 24 kWp study",
        body: "Hello,\n\nWith your cold rooms running during the day, your self-consumption share should exceed 70 % — the case where payback is fastest.\n\nThe attached study is based on your meter readings. I can come and check the shed's structure next week." } } },
  { id: "l06", day: 7, score: 22, accepted: false, source: "formulaire",
    fr: { name: "Démarchage · fournisseur de panneaux", request: "Proposition de référencement matériel.",
      verdict: "Hors sujet.",
      rejected: "Sollicitation fournisseur. Écartée sans réponse." },
    en: { name: "Cold outreach · panel supplier", request: "Equipment listing proposal.",
      verdict: "Off-topic.",
      rejected: "Supplier solicitation. Discarded without reply." } },
  { id: "l07", day: 9, score: 76, accepted: true, source: "simulateur",
    fr: { name: "M. et Mme Roussel · Clermont-l'Hérault", request: "Toiture double pan, 12 kWc envisagés, facture annuelle 3 400 €.",
      verdict: "Consommation élevée, toiture exploitable sur deux pans.",
      email: { subject: "Étude 12 kWc — toiture double pan",
        body: "Bonjour,\n\nSur une toiture à deux pans, nous répartissons les modules pour lisser la production sur la journée plutôt que de tout concentrer à midi.\n\nL'étude jointe compare cette répartition avec une pose sur le seul pan sud." } },
    en: { name: "Mr & Mrs Roussel · Clermont-l'Hérault", request: "Dual-pitch roof, 12 kWp considered, €3,400 annual bill.",
      verdict: "High consumption, roof usable on both pitches.",
      email: { subject: "12 kWp study — dual-pitch roof",
        body: "Hello,\n\nOn a dual-pitch roof we spread the modules to even out output across the day rather than concentrating everything at midday.\n\nThe attached study compares that split with an installation on the south pitch alone." } } },
  { id: "l08", day: 12, score: 34, accepted: false, source: "simulateur",
    fr: { name: "M. Salles · Gigean", request: "Toiture ombragée par un bâtiment voisin sur les deux tiers.",
      verdict: "Ombrage trop important pour un rendement acceptable.",
      rejected: "Étude d'ombrage défavorable. Refus argumenté envoyé plutôt qu'un devis de complaisance." },
    en: { name: "Mr Salles · Gigean", request: "Roof shaded by a neighbouring building over two thirds.",
      verdict: "Too much shading for acceptable yield.",
      rejected: "Unfavourable shading study. Reasoned refusal sent rather than a token quote." } },
  { id: "l09", day: 15, score: 82, accepted: true, source: "simulateur",
    fr: { name: "Mme Portal · Villeneuve-lès-Maguelone", request: "8 kWc avec gestionnaire d'énergie, véhicule électrique à recharger.",
      verdict: "Usage identifié, pilotage de charge pertinent.",
      email: { subject: "8 kWc et recharge véhicule",
        body: "Bonjour,\n\nAvec un véhicule électrique, le gestionnaire d'énergie change tout : il décale la recharge sur les heures de production plutôt que sur le réseau.\n\nL'étude jointe chiffre l'écart entre une pose simple et une pose pilotée." } },
    en: { name: "Ms Portal · Villeneuve-lès-Maguelone", request: "8 kWp with an energy manager, electric vehicle to charge.",
      verdict: "Clear use case, load control relevant.",
      email: { subject: "8 kWp and vehicle charging",
        body: "Hello,\n\nWith an electric vehicle, the energy manager changes everything: it shifts charging to generating hours rather than the grid.\n\nThe attached study prices the gap between a plain installation and a managed one." } } },
  { id: "l10", day: 19, score: 29, accepted: false, source: "formulaire",
    fr: { name: "Toiture fibrociment · Vias", request: "Projet 5 kWc sur toiture des années 80.",
      verdict: "Diagnostic amiante requis avant toute étude.",
      rejected: "Pose exclue sans désamiantage préalable. Marche à suivre envoyée, dossier en attente." },
    en: { name: "Fibre-cement roof · Vias", request: "5 kWp project on an eighties roof.",
      verdict: "Asbestos survey required before any study.",
      rejected: "Installation ruled out without prior removal. Steps sent, file on hold." } },
  { id: "l11", day: 23, score: 79, accepted: true, source: "telephone",
    fr: { name: "Garage Aubin · Lattes", request: "30 kWc en toiture plus ombrières de parking, autorisation d'urbanisme à monter.",
      verdict: "Client professionnel, double lot, dossier administratif à porter.",
      email: { subject: "Toiture et ombrières — dossier complet",
        body: "Bonjour,\n\nLes ombrières relèvent d'une autorisation d'urbanisme que nous préparons et déposons pour vous : c'est le poste qui bloque le plus souvent ce type de projet.\n\nL'étude jointe sépare la toiture et les ombrières pour que vous puissiez décider lot par lot." } },
    en: { name: "Aubin garage · Lattes", request: "30 kWp on the roof plus car-park canopies, planning application to prepare.",
      verdict: "Trade client, two packages, planning file to carry.",
      email: { subject: "Roof and canopies — full application",
        body: "Hello,\n\nThe canopies require planning consent, which we prepare and file for you: that is the item that most often stalls this kind of project.\n\nThe attached study separates roof and canopies so you can decide package by package." } } },
  { id: "l12", day: 28, score: 85, accepted: true, source: "recommandation",
    fr: { name: "M. Fabre · Poussan", request: "10 kWc et batterie 8 kWh, autoconsommation maximale, adressé par un voisin équipé.",
      verdict: "Recommandation, objectif clair, budget confirmé.",
      email: { subject: "10 kWc et batterie — autoconsommation",
        body: "Bonjour,\n\nPour viser l'autoconsommation maximale, la taille de la batterie compte moins que le pilotage : au-delà de 8 kWh, le gain marginal chute.\n\nL'étude jointe montre le point où l'ajout de capacité cesse d'être rentable chez vous." } },
    en: { name: "Mr Fabre · Poussan", request: "10 kWp and 8 kWh battery, maximum self-consumption, referred by an equipped neighbour.",
      verdict: "Referral, clear objective, confirmed budget.",
      email: { subject: "10 kWp and battery — self-consumption",
        body: "Hello,\n\nTo maximise self-consumption, battery size matters less than control: beyond 8 kWh, the marginal gain drops off.\n\nThe attached study shows the point where adding capacity stops paying in your case." } } },
  { id: "l13", day: 39, score: 90, accepted: true, source: "recommandation",
    fr: { name: "Coopérative agricole · Marsillargues", request: "Bâtiment de stockage 600 m², 28 kWc, décision en conseil d'administration.",
      verdict: "Gros volume, décision collective mais budget voté.",
      email: { subject: "Bâtiment de stockage — 28 kWc",
        body: "Bonjour,\n\nPour un passage en conseil d'administration, nous fournissons un dossier avec plan de financement et projection de production sur vingt ans.\n\nJe peux présenter l'étude en séance si cela facilite la décision." } },
    en: { name: "Farmers' cooperative · Marsillargues", request: "600 m² storage building, 28 kWp, board decision.",
      verdict: "Large volume, collective decision but budget approved.",
      email: { subject: "Storage building — 28 kWp",
        body: "Hello,\n\nFor a board meeting we provide a pack with a financing plan and a twenty-year output projection.\n\nI can present the study in person if that helps the decision." } } },
  { id: "l14", day: 58, score: 73, accepted: true, source: "simulateur",
    fr: { name: "M. et Mme Brun · Castelnau-le-Lez", request: "14 kWc avec batterie 15 kWh, maison neuve RE2020.",
      verdict: "Construction neuve, dimensionnement à caler avec le constructeur.",
      email: { subject: "Maison RE2020 — dimensionnement",
        body: "Bonjour,\n\nSur une maison RE2020, les besoins réels sont souvent inférieurs à l'estimation initiale : mieux vaut caler la puissance sur la consommation mesurée après un an.\n\nJe vous propose une pose en deux temps pour éviter le surdimensionnement." } },
    en: { name: "Mr & Mrs Brun · Castelnau-le-Lez", request: "14 kWp with 15 kWh battery, new-build to the latest energy standard.",
      verdict: "New build, sizing to settle with the housebuilder.",
      email: { subject: "New-build home — sizing",
        body: "Hello,\n\nIn a new build to current standards, real demand is often below the initial estimate: better to size the system on measured consumption after a year.\n\nI suggest a two-stage installation to avoid oversizing." } } },
  { id: "l15", day: 76, score: 68, accepted: true, source: "telephone",
    fr: { name: "Logistique Sud · Vendargues", request: "Entrepôt 1 200 m², 40 kWc, contrainte de non-interruption d'activité.",
      verdict: "Gros volume, contrainte d'exploitation à intégrer au planning.",
      email: { subject: "Entrepôt — pose sans interruption",
        body: "Bonjour,\n\nSur un entrepôt en activité, nous travaillons par zones et de nuit si nécessaire : l'exploitation n'est jamais arrêtée plus d'une demi-journée.\n\nLe planning joint détaille le découpage par zone." } },
    en: { name: "Logistique Sud · Vendargues", request: "1,200 m² warehouse, 40 kWp, operations must not stop.",
      verdict: "Large volume, operational constraint to build into the schedule.",
      email: { subject: "Warehouse — installation without downtime",
        body: "Hello,\n\nIn a working warehouse we work zone by zone, and at night if needed: operations are never halted for more than half a day.\n\nThe attached schedule details the zoning." } } },
];

const invoices: Invoice[] = [
  { id: "i01", day: 2,  dueIn: 28, amount: 14200, vatRate: 0.1, paid: true,  category: "residentiel",
    fr: { ref: "F-2026-1184", client: "M. et Mme F. · Béziers" }, en: { ref: "INV-2026-1184", client: "Mr & Mrs F. · Béziers" } },
  { id: "i02", day: 5,  dueIn: 25, amount: 27600, vatRate: 0.1, paid: true,  category: "batterie",
    fr: { ref: "F-2026-1181", client: "M. D. · Narbonne" }, en: { ref: "INV-2026-1181", client: "Mr D. · Narbonne" } },
  { id: "i03", day: 9,  dueIn: 21, amount: 21400, vatRate: 0.1, paid: true,  category: "residentiel",
    fr: { ref: "F-2026-1177", client: "H. Delcourt · Agde" }, en: { ref: "INV-2026-1177", client: "H. Delcourt · Agde" } },
  { id: "i04", day: 13, dueIn: 17, amount: 62400, vatRate: 0.2, paid: false, category: "pro",
    fr: { ref: "F-2026-1172", client: "SCI M. · Montpellier" }, en: { ref: "INV-2026-1172", client: "SCI M. · Montpellier" } },
  { id: "i05", day: 17, dueIn: 13, amount: 12600, vatRate: 0.1, paid: true,  category: "residentiel",
    fr: { ref: "F-2026-1168", client: "Mme Cazals · Mèze" }, en: { ref: "INV-2026-1168", client: "Ms Cazals · Mèze" } },
  { id: "i06", day: 21, dueIn: 9,  amount: 4800,  vatRate: 0.2, paid: false, category: "sav",
    fr: { ref: "F-2026-1163", client: "M. Vernet · Balaruc" }, en: { ref: "INV-2026-1163", client: "Mr Vernet · Balaruc" } },
  { id: "i07", day: 25, dueIn: -4, amount: 18500, vatRate: 0.1, paid: false, category: "residentiel",
    fr: { ref: "F-2026-1158", client: "Mme Portal · Villeneuve" }, en: { ref: "INV-2026-1158", client: "Ms Portal · Villeneuve" } },
  { id: "i08", day: 29, dueIn: 1,  amount: 23800, vatRate: 0.1, paid: true,  category: "batterie",
    fr: { ref: "F-2026-1154", client: "M. Fabre · Poussan" }, en: { ref: "INV-2026-1154", client: "Mr Fabre · Poussan" } },
  { id: "i09", day: 38, dueIn: 22, amount: 44600, vatRate: 0.2, paid: true,  category: "pro",
    fr: { ref: "F-2026-1145", client: "Coopérative · Marsillargues" }, en: { ref: "INV-2026-1145", client: "Cooperative · Marsillargues" } },
  { id: "i10", day: 47, dueIn: -11, amount: 9600, vatRate: 0.2, paid: false, category: "sav",
    fr: { ref: "F-2026-1136", client: "M. Teissier · Vias" }, en: { ref: "INV-2026-1136", client: "Mr Teissier · Vias" } },
  { id: "i11", day: 57, dueIn: 3,  amount: 32100, vatRate: 0.1, paid: true,  category: "batterie",
    fr: { ref: "F-2026-1124", client: "M. et Mme Brun · Castelnau" }, en: { ref: "INV-2026-1124", client: "Mr & Mrs Brun · Castelnau" } },
  { id: "i12", day: 66, dueIn: 14, amount: 17900, vatRate: 0.1, paid: true,  category: "residentiel",
    fr: { ref: "F-2026-1112", client: "Mme Granier · Bouzigues" }, en: { ref: "INV-2026-1112", client: "Ms Granier · Bouzigues" } },
  { id: "i13", day: 75, dueIn: 5,  amount: 58300, vatRate: 0.2, paid: true,  category: "pro",
    fr: { ref: "F-2026-1098", client: "Logistique Sud · Vendargues" }, en: { ref: "INV-2026-1098", client: "Logistique Sud · Vendargues" } },
];

export const SOLAIRE_DATA: SectorData = {
  company: "Héliade Énergies",
  quotes,
  calls,
  leads,
  invoices,
  categories: [
    { key: "residentiel", fr: "Résidentiel", en: "Residential" },
    { key: "batterie", fr: "Avec stockage", en: "With storage" },
    { key: "pro", fr: "Professionnel & agricole", en: "Commercial & farming" },
    { key: "sav", fr: "SAV & maintenance", en: "Service & maintenance" },
  ],
  sources: [
    { key: "simulateur", fr: "Simulateur en ligne", en: "Online simulator" },
    { key: "formulaire", fr: "Formulaire du site", en: "Website form" },
    { key: "telephone", fr: "Appel entrant", en: "Inbound call" },
    { key: "recommandation", fr: "Recommandation", en: "Referral" },
  ],
};
