import type { Call, Invoice, Lead, Quote, SectorData } from "./types";

/**
 * Pisciniste. DONNÉES ENTIÈREMENT FICTIVES.
 *
 * Le vocabulaire suit celui de la page secteur (lib/sectors.ts) : saison qui
 * sature, devis à J+10, hivernages oubliés, financement multi-acteurs. Les
 * communes sont celles du Chablais, cohérentes avec l'implantation affichée
 * dans le pied de page.
 *
 * Les chiffres sont écrits une fois ; compteurs, graphiques et totaux en sont
 * dérivés. Aucun total n'est saisi à la main : c'est ce qui évite qu'un KPI
 * contredise le tableau juste en dessous, ce qui arrivait dans la version
 * précédente.
 */

const quotes: Quote[] = [
  { id: "q01", day: 2,  amount: 32400, reminders: 0, outcome: "pending", category: "construction",
    fr: { client: "Famille M. · Publier", project: "Coque 8×4 + local technique" },
    en: { client: "M. family · Publier", project: "8×4 shell + plant room" } },
  { id: "q02", day: 3,  amount: 11800, reminders: 0, outcome: "pending", category: "renovation",
    fr: { client: "M. B. · Thonon-les-Bains", project: "Rénovation liner + margelles" },
    en: { client: "Mr B. · Thonon-les-Bains", project: "Liner + coping renovation" } },
  { id: "q03", day: 5,  amount: 9200,  reminders: 1, outcome: "pending", category: "abri",
    fr: { client: "Mme D. · Évian", project: "Abri télescopique bas" },
    en: { client: "Ms D. · Évian", project: "Low telescopic enclosure" } },
  { id: "q04", day: 6,  amount: 4300,  reminders: 1, outcome: "win", category: "entretien",
    fr: { client: "Copropriété Les Tilleuls · Amphion", project: "Contrat entretien annuel · 2 bassins" },
    en: { client: "Les Tilleuls residence · Amphion", project: "Annual maintenance contract · 2 pools" } },
  { id: "q05", day: 8,  amount: 27600, reminders: 0, outcome: "pending", category: "construction",
    fr: { client: "M. et Mme R. · Sciez", project: "Bassin béton 9×4 + plage immergée" },
    en: { client: "Mr & Mrs R. · Sciez", project: "9×4 concrete pool + wet deck" } },
  { id: "q06", day: 9,  amount: 6800,  reminders: 2, outcome: "win", category: "equipement",
    fr: { client: "M. L. · Anthy-sur-Léman", project: "Pompe à chaleur 12 kW + bâche à barres" },
    en: { client: "Mr L. · Anthy-sur-Léman", project: "12 kW heat pump + bar cover" } },
  { id: "q07", day: 11, amount: 15400, reminders: 1, outcome: "pending", category: "renovation",
    fr: { client: "Hôtel du Rivage · Évian", project: "Reprise étanchéité + filtration" },
    en: { client: "Hôtel du Rivage · Évian", project: "Waterproofing + filtration overhaul" } },
  { id: "q08", day: 12, amount: 2900,  reminders: 0, outcome: "win", category: "entretien",
    fr: { client: "Mme P. · Douvaine", project: "Hivernage + remise en route" },
    en: { client: "Ms P. · Douvaine", project: "Winterising + spring restart" } },
  { id: "q09", day: 14, amount: 38900, reminders: 1, outcome: "pending", category: "construction",
    fr: { client: "M. C. · Yvoire", project: "Miroir d'eau 10×4 + escalier maçonné" },
    en: { client: "Mr C. · Yvoire", project: "10×4 infinity pool + built-in steps" } },
  { id: "q10", day: 15, amount: 7400,  reminders: 3, outcome: "loss", category: "abri",
    fr: { client: "M. et Mme T. · Margencel", project: "Abri mi-haut 3 modules" },
    en: { client: "Mr & Mrs T. · Margencel", project: "Mid-height 3-module enclosure" } },
  { id: "q11", day: 17, amount: 5200,  reminders: 2, outcome: "pending", category: "equipement",
    fr: { client: "M. V. · Lugrin", project: "Électrolyseur au sel + régulation pH" },
    en: { client: "Mr V. · Lugrin", project: "Salt chlorinator + pH control" } },
  { id: "q12", day: 18, amount: 3600,  reminders: 0, outcome: "win", category: "entretien",
    fr: { client: "Camping du Lac · Excenevex", project: "Entretien bi-hebdomadaire · saison" },
    en: { client: "Camping du Lac · Excenevex", project: "Twice-weekly maintenance · season" } },
  { id: "q13", day: 20, amount: 21300, reminders: 1, outcome: "pending", category: "renovation",
    fr: { client: "Mme G. · Neuvecelle", project: "Transformation bassin béton + PAC" },
    en: { client: "Ms G. · Neuvecelle", project: "Concrete pool conversion + heat pump" } },
  { id: "q14", day: 22, amount: 12700, reminders: 2, outcome: "pending", category: "abri",
    fr: { client: "M. F. · Marin", project: "Abri haut adossé + terrasse mobile" },
    en: { client: "Mr F. · Marin", project: "Lean-to high enclosure + moving floor" } },
  { id: "q15", day: 23, amount: 8100,  reminders: 3, outcome: "loss", category: "equipement",
    fr: { client: "M. S. · Allinges", project: "Nage à contre-courant + éclairage LED" },
    en: { client: "Mr S. · Allinges", project: "Counter-current unit + LED lighting" } },
  { id: "q16", day: 25, amount: 4900,  reminders: 1, outcome: "pending", category: "entretien",
    fr: { client: "Mme H. · Perrignier", project: "Contrat entretien + hivernage" },
    en: { client: "Ms H. · Perrignier", project: "Maintenance contract + winterising" } },
  { id: "q17", day: 26, amount: 29800, reminders: 0, outcome: "pending", category: "construction",
    fr: { client: "M. et Mme N. · Bons-en-Chablais", project: "Coque 9×4 + plage bois exotique" },
    en: { client: "Mr & Mrs N. · Bons-en-Chablais", project: "9×4 shell + hardwood deck" } },
  { id: "q18", day: 27, amount: 6300,  reminders: 2, outcome: "pending", category: "renovation",
    fr: { client: "M. J. · Thonon-les-Bains", project: "Remplacement filtre à sable + vannes" },
    en: { client: "Mr J. · Thonon-les-Bains", project: "Sand filter + valve replacement" } },
  { id: "q19", day: 29, amount: 17500, reminders: 1, outcome: "pending", category: "renovation",
    fr: { client: "Résidence Beauregard · Publier", project: "Reprise plage + garde-corps" },
    en: { client: "Beauregard residence · Publier", project: "Deck + guardrail rework" } },
  { id: "q20", day: 30, amount: 3100,  reminders: 0, outcome: "pending", category: "entretien",
    fr: { client: "M. A. · Sciez", project: "Diagnostic fuite + traitement choc" },
    en: { client: "Mr A. · Sciez", project: "Leak diagnosis + shock treatment" } },

  { id: "q29", day: 7,  amount: 19800, reminders: 2, outcome: "win", category: "construction",
    fr: { client: "M. et Mme Q. · Excenevex", project: "Coque 8×4 + terrasse composite" },
    en: { client: "Mr & Mrs Q. · Excenevex", project: "8×4 shell + composite deck" } },
  { id: "q30", day: 19, amount: 6100,  reminders: 1, outcome: "win", category: "abri",
    fr: { client: "Mme Z. · Douvaine", project: "Abri bas 3 modules" },
    en: { client: "Ms Z. · Douvaine", project: "Low 3-module enclosure" } },

  // Au-delà de 30 jours : visibles seulement en vue 90 jours.
  { id: "q21", day: 38, amount: 24100, reminders: 2, outcome: "win", category: "construction",
    fr: { client: "M. et Mme K. · Évian", project: "Coque 7×3,5 + volet immergé" },
    en: { client: "Mr & Mrs K. · Évian", project: "7×3.5 shell + submerged cover" } },
  { id: "q22", day: 44, amount: 9800,  reminders: 3, outcome: "loss", category: "abri",
    fr: { client: "M. D. · Douvaine", project: "Abri plat motorisé" },
    en: { client: "Mr D. · Douvaine", project: "Motorised flat enclosure" } },
  { id: "q23", day: 51, amount: 5600,  reminders: 1, outcome: "win", category: "equipement",
    fr: { client: "Mme B. · Anthy-sur-Léman", project: "Robot nettoyeur + coffret filtration" },
    en: { client: "Ms B. · Anthy-sur-Léman", project: "Cleaning robot + filtration cabinet" } },
  { id: "q24", day: 58, amount: 33200, reminders: 1, outcome: "win", category: "construction",
    fr: { client: "M. O. · Yvoire", project: "Bassin béton 10×5 + local enterré" },
    en: { client: "Mr O. · Yvoire", project: "10×5 concrete pool + buried plant room" } },
  { id: "q25", day: 63, amount: 4200,  reminders: 2, outcome: "loss", category: "entretien",
    fr: { client: "M. R. · Lugrin", project: "Contrat entretien mensuel" },
    en: { client: "Mr R. · Lugrin", project: "Monthly maintenance contract" } },
  { id: "q26", day: 71, amount: 13900, reminders: 1, outcome: "win", category: "renovation",
    fr: { client: "Mme W. · Marin", project: "Liner armé + projecteurs" },
    en: { client: "Ms W. · Marin", project: "Reinforced liner + underwater lights" } },
  { id: "q27", day: 79, amount: 7900,  reminders: 0, outcome: "win", category: "abri",
    fr: { client: "M. E. · Perrignier", project: "Abri bas coulissant 4 modules" },
    en: { client: "Mr E. · Perrignier", project: "Low sliding 4-module enclosure" } },
  { id: "q28", day: 86, amount: 18600, reminders: 2, outcome: "win", category: "renovation",
    fr: { client: "Hôtel des Cygnes · Thonon-les-Bains", project: "Rénovation complète bassin intérieur" },
    en: { client: "Hôtel des Cygnes · Thonon-les-Bains", project: "Full indoor pool renovation" } },
];

const calls: Call[] = [
  { id: "c01", day: 0, minute: 561, durationSec: 148, urgent: true, outcome: "escalated",
    fr: {
      from: "06 12 •• •• 34",
      summary: "Eau verte depuis deux jours, réception prévue samedi.",
      transcript: [
        { who: "client", text: "Bonjour, l'eau est devenue verte du jour au lendemain, et on reçoit du monde samedi." },
        { who: "ia", text: "Je note. Le traitement au chlore est-il automatique chez vous, ou manuel ?" },
        { who: "client", text: "Automatique, mais le voyant rouge clignote depuis mardi." },
        { who: "ia", text: "Ça oriente vers la sonde de régulation. Je passe le dossier en priorité, un technicien vous rappelle avant midi." },
      ],
      action: "Escaladé au SAV · créneau réservé jeudi 8h",
    },
    en: {
      from: "06 12 •• •• 34",
      summary: "Green water for two days, guests due Saturday.",
      transcript: [
        { who: "client", text: "Hello, the water turned green overnight and we have people over on Saturday." },
        { who: "ia", text: "Noted. Is your chlorine dosing automatic or manual?" },
        { who: "client", text: "Automatic, but the red light has been flashing since Tuesday." },
        { who: "ia", text: "That points to the control probe. I am flagging this as a priority — a technician will ring you before noon." },
      ],
      action: "Escalated to callouts · slot booked Thursday 8am",
    } },

  // Transcription reprise de la première version : elle montre bien l'agent qui
  // écarte les causes simples avant d'escalader, ce qui est l'argument du bloc.
  { id: "c02", day: 0, minute: 521, durationSec: 194, urgent: true, outcome: "escalated",
    fr: {
      from: "04 50 •• •• 76",
      summary: "Client sous contrat. Pompe qui siffle et perte de pression depuis deux jours ; l'agent a écarté les causes simples.",
      transcript: [
        { who: "client", text: "La pompe fait un bruit anormal depuis avant-hier, et j'ai moins de pression." },
        { who: "ia", text: "Je vérifie votre contrat… vous êtes bien couvert. Le panier du préfiltre est propre ?" },
        { who: "client", text: "Oui, je l'ai vidé hier, ça n'a rien changé." },
        { who: "ia", text: "Et le niveau d'eau, il est au-dessus du milieu des skimmers ?" },
        { who: "client", text: "Oui, niveau normal." },
        { who: "ia", text: "Alors ce n'est pas un désamorçage. Je passe le dossier en intervention, un technicien vous rappelle ce matin." },
      ],
      action: "SAV sous contrat · escaladé",
    },
    en: {
      from: "04 50 •• •• 76",
      summary: "Client under contract. Whining pump and pressure loss for two days; the agent ruled out the simple causes first.",
      transcript: [
        { who: "client", text: "The pump has been making an odd noise since the day before yesterday, and I have less pressure." },
        { who: "ia", text: "Let me check your contract… you are covered. Is the pre-filter basket clean?" },
        { who: "client", text: "Yes, I emptied it yesterday, it made no difference." },
        { who: "ia", text: "And the water level, is it above the middle of the skimmers?" },
        { who: "client", text: "Yes, normal level." },
        { who: "ia", text: "Then it is not losing prime. I am moving this to a callout — a technician will ring you this morning." },
      ],
      action: "Contract callout · escalated",
    } },
  { id: "c03", day: 0, minute: 634, durationSec: 96, urgent: false, outcome: "handled",
    fr: {
      from: "04 50 •• •• 71",
      summary: "Délai de pose pour un abri télescopique.",
      transcript: [
        { who: "client", text: "J'ai reçu le devis pour l'abri, je voulais savoir sous combien de temps vous posez." },
        { who: "ia", text: "Pour un télescopique bas, comptez six à huit semaines entre la commande et la pose." },
        { who: "client", text: "D'accord. Et la déclaration de travaux, c'est vous qui la faites ?" },
        { who: "ia", text: "Oui, on la prépare et on la dépose. Je vous envoie le récapitulatif par mail." },
      ],
      action: "Récapitulatif envoyé · relance du devis suspendue",
    },
    en: {
      from: "04 50 •• •• 71",
      summary: "Lead time on a telescopic enclosure.",
      transcript: [
        { who: "client", text: "I got the quote for the enclosure — how long before you can install it?" },
        { who: "ia", text: "For a low telescopic model, allow six to eight weeks between order and installation." },
        { who: "client", text: "Right. And do you handle the planning notice?" },
        { who: "ia", text: "We do — we prepare it and file it. I am sending you the summary by email." },
      ],
      action: "Summary sent · quote sequence paused",
    } },
  { id: "c04", day: 1, minute: 522, durationSec: 210, urgent: false, outcome: "handled",
    fr: {
      from: "06 78 •• •• 09",
      summary: "Chiffrage d'un hivernage pour deux bassins en copropriété.",
      transcript: [
        { who: "client", text: "On a deux bassins sur la copropriété, il faudrait un hivernage actif." },
        { who: "ia", text: "Deux bassins de quelle taille environ ?" },
        { who: "client", text: "Un de 10 sur 5 et un petit bain de 4 sur 3." },
        { who: "ia", text: "Je transmets au commercial avec ces éléments. Vous aurez un devis sous 48 heures." },
      ],
      action: "Transmis · devis en préparation",
    },
    en: {
      from: "06 78 •• •• 09",
      summary: "Pricing active winterising for two pools on an estate.",
      transcript: [
        { who: "client", text: "We have two pools on the estate — we would need active winterising." },
        { who: "ia", text: "Roughly what size are the two pools?" },
        { who: "client", text: "One is 10 by 5, plus a small 4 by 3 paddling pool." },
        { who: "ia", text: "I am passing this to a salesperson with those details. You will have a quote within 48 hours." },
      ],
      action: "Passed on · quote in preparation",
    } },
  { id: "c05", day: 1, minute: 705, durationSec: 64, urgent: false, outcome: "handled",
    fr: {
      from: "07 61 •• •• 25",
      summary: "Horaires du magasin et disponibilité d'un robot.",
      transcript: [
        { who: "client", text: "Vous êtes ouverts samedi ? Et vous avez des robots en stock ?" },
        { who: "ia", text: "Ouvert samedi de 9h à 12h. Trois modèles de robots sont disponibles en magasin." },
      ],
      action: "Réponse donnée · aucune suite nécessaire",
    },
    en: {
      from: "07 61 •• •• 25",
      summary: "Shop hours and robot availability.",
      transcript: [
        { who: "client", text: "Are you open on Saturday? And do you have cleaning robots in stock?" },
        { who: "ia", text: "Open Saturday 9am to noon. Three robot models are in stock at the shop." },
      ],
      action: "Answered · no follow-up needed",
    } },
  { id: "c06", day: 2, minute: 597, durationSec: 187, urgent: true, outcome: "escalated",
    fr: {
      from: "06 34 •• •• 88",
      summary: "Fuite suspectée, niveau qui baisse de trois centimètres par jour.",
      transcript: [
        { who: "client", text: "Le niveau baisse de trois centimètres par jour depuis une semaine." },
        { who: "ia", text: "Avez-vous constaté de l'humidité autour du local technique ?" },
        { who: "client", text: "Oui, la dalle est mouillée en permanence." },
        { who: "ia", text: "Ça oriente vers une fuite sur canalisation. Je passe en priorité, un technicien vous rappelle aujourd'hui." },
      ],
      action: "Escaladé au SAV · recherche de fuite planifiée",
    },
    en: {
      from: "06 34 •• •• 88",
      summary: "Suspected leak, level dropping three centimetres a day.",
      transcript: [
        { who: "client", text: "The level has been dropping three centimetres a day for a week." },
        { who: "ia", text: "Have you noticed damp around the plant room?" },
        { who: "client", text: "Yes, the slab is permanently wet." },
        { who: "ia", text: "That points to a pipework leak. I am marking this priority — a technician will call you today." },
      ],
      action: "Escalated to callouts · leak survey scheduled",
    } },
  { id: "c07", day: 3, minute: 488, durationSec: 132, urgent: false, outcome: "handled",
    fr: {
      from: "04 50 •• •• 12",
      summary: "Modalités de paiement sur une construction.",
      transcript: [
        { who: "client", text: "Vous proposez du paiement en plusieurs fois pour une construction à 30 000 € ?" },
        { who: "ia", text: "Oui, échelonnement en trois appels de fonds : commande, terrassement, mise en eau." },
        { who: "client", text: "Et un financement bancaire, vous travaillez avec quelqu'un ?" },
        { who: "ia", text: "On a un partenaire. Je vous envoie sa fiche et je préviens votre commercial." },
      ],
      action: "Fiche partenaire envoyée · commercial prévenu",
    },
    en: {
      from: "04 50 •• •• 12",
      summary: "Payment terms on a new build.",
      transcript: [
        { who: "client", text: "Do you offer instalments on a €30,000 build?" },
        { who: "ia", text: "We do — three stage payments: order, excavation, filling." },
        { who: "client", text: "And bank finance, do you work with anyone?" },
        { who: "ia", text: "We have a partner. I am sending you their details and alerting your salesperson." },
      ],
      action: "Partner details sent · salesperson alerted",
    } },
  { id: "c08", day: 4, minute: 668, durationSec: 78, urgent: false, outcome: "handled",
    fr: {
      from: "06 22 •• •• 47",
      summary: "Report d'un passage d'entretien.",
      transcript: [
        { who: "client", text: "Je ne serai pas là mardi, on peut décaler le passage ?" },
        { who: "ia", text: "Je vous propose jeudi même heure, ça vous convient ?" },
        { who: "client", text: "Parfait." },
      ],
      action: "Rendez-vous déplacé · agenda mis à jour",
    },
    en: {
      from: "06 22 •• •• 47",
      summary: "Rescheduling a maintenance visit.",
      transcript: [
        { who: "client", text: "I will not be here on Tuesday — can we move the visit?" },
        { who: "ia", text: "I can offer Thursday at the same time, does that work?" },
        { who: "client", text: "Perfect." },
      ],
      action: "Visit moved · calendar updated",
    } },
  { id: "c09", day: 6, minute: 545, durationSec: 155, urgent: false, outcome: "handled",
    fr: {
      from: "07 08 •• •• 63",
      summary: "Pompe à chaleur bruyante six mois après la pose.",
      transcript: [
        { who: "client", text: "La PAC fait un bruit de ferraille depuis quelques jours." },
        { who: "ia", text: "Elle a été posée quand ?" },
        { who: "client", text: "En avril, chez vous." },
        { who: "ia", text: "Vous êtes sous garantie. Je crée un ticket SAV, sans frais de déplacement." },
      ],
      action: "Ticket SAV créé sous garantie",
    },
    en: {
      from: "07 08 •• •• 63",
      summary: "Heat pump rattling six months after installation.",
      transcript: [
        { who: "client", text: "The heat pump has been making a rattling noise for a few days." },
        { who: "ia", text: "When was it installed?" },
        { who: "client", text: "In April, by you." },
        { who: "ia", text: "You are still under warranty. I am opening a service ticket, no call-out fee." },
      ],
      action: "Warranty service ticket opened",
    } },
  { id: "c10", day: 9, minute: 612, durationSec: 118, urgent: false, outcome: "handled",
    fr: {
      from: "06 90 •• •• 51",
      summary: "Demande de chiffrage pour un passage au sel.",
      transcript: [
        { who: "client", text: "Je voudrais passer au sel, vous faites ça ?" },
        { who: "ia", text: "Oui. Quel volume fait votre bassin ?" },
        { who: "client", text: "Environ 50 mètres cubes." },
        { who: "ia", text: "Je transmets pour chiffrage, vous aurez le devis demain." },
      ],
      action: "Transmis · devis créé",
    },
    en: {
      from: "06 90 •• •• 51",
      summary: "Pricing request for a switch to salt water.",
      transcript: [
        { who: "client", text: "I would like to switch to salt — do you do that?" },
        { who: "ia", text: "We do. What is the volume of your pool?" },
        { who: "client", text: "Around 50 cubic metres." },
        { who: "ia", text: "I am passing it on for pricing — you will have the quote tomorrow." },
      ],
      action: "Passed on · quote created",
    } },
  { id: "c11", day: 13, minute: 501, durationSec: 92, urgent: false, outcome: "handled",
    fr: {
      from: "04 50 •• •• 39",
      summary: "Précision sur la garantie d'un liner armé.",
      transcript: [
        { who: "client", text: "J'ai reçu le devis liner, je voulais des précisions sur la garantie." },
        { who: "ia", text: "Le liner armé est garanti dix ans, pose comprise." },
        { who: "client", text: "D'accord, je vous réponds cette semaine." },
      ],
      action: "Relance suspendue · rappel programmé J+5",
    },
    en: {
      from: "04 50 •• •• 39",
      summary: "Warranty question on a reinforced liner.",
      transcript: [
        { who: "client", text: "I got the liner quote — I wanted to check the warranty." },
        { who: "ia", text: "The reinforced liner is guaranteed ten years, installation included." },
        { who: "client", text: "Good, I will get back to you this week." },
      ],
      action: "Sequence paused · reminder set for D+5",
    } },
  { id: "c12", day: 16, minute: 720, durationSec: 203, urgent: true, outcome: "escalated",
    fr: {
      from: "06 45 •• •• 77",
      summary: "Volet immergé bloqué en position ouverte.",
      transcript: [
        { who: "client", text: "Le volet ne se referme plus, il est resté ouvert." },
        { who: "ia", text: "Entendez-vous le moteur tourner quand vous actionnez la clé ?" },
        { who: "client", text: "Non, rien du tout." },
        { who: "ia", text: "Coupure d'alimentation probable. Je passe en SAV prioritaire, c'est un enjeu de sécurité." },
      ],
      action: "Escaladé au SAV · intervention sous 24h",
    },
    en: {
      from: "06 45 •• •• 77",
      summary: "Submerged cover stuck open.",
      transcript: [
        { who: "client", text: "The cover will not close any more, it is stuck open." },
        { who: "ia", text: "Can you hear the motor turning when you use the key?" },
        { who: "client", text: "No, nothing at all." },
        { who: "ia", text: "Likely a power cut to the unit. I am escalating as a priority — this is a safety issue." },
      ],
      action: "Escalated to callouts · visit within 24h",
    } },
  { id: "c13", day: 21, minute: 559, durationSec: 87, urgent: false, outcome: "handled",
    fr: {
      from: "07 33 •• •• 14",
      summary: "Prix d'une bâche à barres sur mesure.",
      transcript: [
        { who: "client", text: "Combien pour une bâche à barres sur un 8 sur 4 ?" },
        { who: "ia", text: "Comptez entre 1 200 et 1 800 € selon la finition. Je vous envoie la grille." },
      ],
      action: "Grille tarifaire envoyée",
    },
    en: {
      from: "07 33 •• •• 14",
      summary: "Price for a made-to-measure bar cover.",
      transcript: [
        { who: "client", text: "How much for a bar cover on an 8 by 4?" },
        { who: "ia", text: "Between €1,200 and €1,800 depending on the finish. I am sending you the price list." },
      ],
      action: "Price list sent",
    } },
  { id: "c14", day: 26, minute: 480, durationSec: 141, urgent: false, outcome: "handled",
    fr: {
      from: "06 55 •• •• 02",
      summary: "Reprise d'un chantier laissé par un autre installateur.",
      transcript: [
        { who: "client", text: "J'ai un bassin commencé par quelqu'un qui a arrêté. Vous reprenez ce genre de dossier ?" },
        { who: "ia", text: "Oui, après visite technique. Il faut qu'un conducteur de travaux voie l'état du chantier." },
        { who: "client", text: "On peut caler ça quand ?" },
        { who: "ia", text: "Je propose une visite la semaine prochaine, un commercial vous confirme le créneau." },
      ],
      action: "Visite technique à programmer · transmis",
    },
    en: {
      from: "06 55 •• •• 02",
      summary: "Taking over a site abandoned by another installer.",
      transcript: [
        { who: "client", text: "I have a pool started by someone who walked off. Do you take over that kind of job?" },
        { who: "ia", text: "We do, after a site visit. A works manager needs to see the current state." },
        { who: "client", text: "When could we arrange that?" },
        { who: "ia", text: "I suggest a visit next week — a salesperson will confirm the slot." },
      ],
      action: "Site visit to be scheduled · passed on",
    } },
  { id: "c15", day: 34, minute: 640, durationSec: 109, urgent: false, outcome: "handled",
    fr: {
      from: "04 50 •• •• 58",
      summary: "Calendrier des remises en route de printemps.",
      transcript: [
        { who: "client", text: "Vous passez quand pour les remises en route ?" },
        { who: "ia", text: "À partir de mi-avril, dans l'ordre des contrats. Vous êtes sur la liste." },
      ],
      action: "Réponse donnée · aucune suite nécessaire",
    },
    en: {
      from: "04 50 •• •• 58",
      summary: "Schedule for spring restarts.",
      transcript: [
        { who: "client", text: "When do you come round for spring restarts?" },
        { who: "ia", text: "From mid-April, in contract order. You are on the list." },
      ],
      action: "Answered · no follow-up needed",
    } },
  { id: "c16", day: 47, minute: 533, durationSec: 174, urgent: false, outcome: "handled",
    fr: {
      from: "06 71 •• •• 30",
      summary: "Comparaison coque et béton pour un projet neuf.",
      transcript: [
        { who: "client", text: "Je ne sais pas quoi choisir entre coque et béton." },
        { who: "ia", text: "La coque est plus rapide à poser, le béton laisse plus de liberté de forme. Quel est votre terrain ?" },
        { who: "client", text: "En pente, assez caillouteux." },
        { who: "ia", text: "Le terrassement pèsera dans les deux cas. Je transmets à un commercial pour une étude." },
      ],
      action: "Transmis · étude de faisabilité demandée",
    },
    en: {
      from: "06 71 •• •• 30",
      summary: "Shell versus concrete for a new build.",
      transcript: [
        { who: "client", text: "I cannot decide between a shell and concrete." },
        { who: "ia", text: "A shell installs faster, concrete gives more freedom of shape. What is your ground like?" },
        { who: "client", text: "Sloped, fairly stony." },
        { who: "ia", text: "Excavation will weigh on both options. I am passing this to a salesperson for a study." },
      ],
      action: "Passed on · feasibility study requested",
    } },
  { id: "c17", day: 62, minute: 585, durationSec: 66, urgent: false, outcome: "handled",
    fr: {
      from: "07 19 •• •• 84",
      summary: "Adresse du dépôt pour un retrait de produits.",
      transcript: [
        { who: "client", text: "Je viens chercher du chlore, c'est bien au dépôt de Marin ?" },
        { who: "ia", text: "Oui, ouvert jusqu'à 17h30. Je vous envoie le lien de l'itinéraire." },
      ],
      action: "Itinéraire envoyé par SMS",
    },
    en: {
      from: "07 19 •• •• 84",
      summary: "Depot address for a product pickup.",
      transcript: [
        { who: "client", text: "I am coming to pick up chlorine — that is the Marin depot, right?" },
        { who: "ia", text: "Yes, open until 5:30pm. I am texting you the directions." },
      ],
      action: "Directions sent by text",
    } },
  { id: "c18", day: 77, minute: 509, durationSec: 121, urgent: false, outcome: "handled",
    fr: {
      from: "06 03 •• •• 96",
      summary: "Tarif d'un hivernage passif pour un bassin de 8×4.",
      transcript: [
        { who: "client", text: "Bonsoir, c'est combien un hivernage pour une piscine de 8 sur 4 ?" },
        { who: "ia", text: "Pour un bassin de cette taille, l'hivernage passif est à 290 € TTC, produits compris." },
        { who: "client", text: "D'accord, et ça se fait quand ?" },
        { who: "ia", text: "Entre mi-octobre et fin novembre, dès que l'eau passe sous 12 °C. Je vous envoie le détail par SMS ?" },
        { who: "client", text: "Oui, merci." },
      ],
      action: "Traité · détail envoyé par SMS",
    },
    en: {
      from: "06 03 •• •• 96",
      summary: "Price of passive winterising for an 8×4 pool.",
      transcript: [
        { who: "client", text: "Good evening, how much is winterising for an 8 by 4 pool?" },
        { who: "ia", text: "For that size, passive winterising is €290 including VAT, products included." },
        { who: "client", text: "Right, and when does that happen?" },
        { who: "ia", text: "Between mid-October and late November, once the water drops below 12 °C. Shall I text you the details?" },
        { who: "client", text: "Yes, thank you." },
      ],
      action: "Handled · details sent by text",
    } },
];

const leads: Lead[] = [
  { id: "l01", day: 0, score: 92, accepted: true, source: "formulaire",
    fr: { name: "C. Vernier · Sciez", request: "Bassin 9×4 enterré, terrain en pente, projet financé, travaux souhaités avant juin.",
      verdict: "Projet cadré, budget confirmé, échéance claire.",
      email: { subject: "Votre projet de bassin 9×4 à Sciez",
        body: "Bonjour,\n\nMerci pour votre demande. Un bassin de 9×4 sur terrain en pente demande une étude de soutènement : c'est le premier point qu'on regardera ensemble sur place.\n\nPour tenir une mise en eau avant juin, il faut caler la visite technique dans les trois semaines. Je vous propose mardi ou jeudi prochain en fin de journée.\n\nQuel créneau vous arrange ?" } },
    en: { name: "C. Vernier · Sciez", request: "9×4 in-ground pool, sloped plot, financing in place, work wanted before June.",
      verdict: "Scoped project, confirmed budget, clear deadline.",
      email: { subject: "Your 9×4 pool project in Sciez",
        body: "Hello,\n\nThank you for your enquiry. A 9×4 pool on a sloped plot needs a retaining study — that is the first thing we will look at together on site.\n\nTo fill before June, the technical visit has to be booked within three weeks. I can offer Tuesday or Thursday next week, late afternoon.\n\nWhich slot suits you?" } } },
  { id: "l02", day: 1, score: 78, accepted: true, source: "formulaire",
    fr: { name: "L. Ferrand · Bons-en-Chablais", request: "Remplacement de liner sur bassin 8×4 de 2009, plus reprise des margelles.",
      verdict: "Besoin précis, mais pas d'échéance ni de budget donné.",
      email: { subject: "Remplacement de liner — bassin 8×4",
        body: "Bonjour,\n\nSur un bassin de 2009, le liner arrive en effet en fin de vie. Avant de chiffrer, deux questions : le support est-il en béton ou en panneaux, et avez-vous constaté des fuites cette saison ?\n\nAvec ces deux réponses je vous envoie une fourchette sous 48 h, margelles comprises." } },
    en: { name: "L. Ferrand · Bons-en-Chablais", request: "Liner replacement on a 2009 8×4 pool, plus coping rework.",
      verdict: "Precise need, but no deadline or budget given.",
      email: { subject: "Liner replacement — 8×4 pool",
        body: "Hello,\n\nOn a 2009 pool the liner is indeed reaching end of life. Before pricing, two questions: is the structure concrete or panel-built, and have you noticed any leaks this season?\n\nWith those two answers I will send you a range within 48 hours, coping included." } } },
  { id: "l03", day: 2, score: 31, accepted: false, source: "formulaire",
    fr: { name: "Demande anonyme", request: "« combien coute une piscine »",
      verdict: "Aucune information exploitable, coordonnées incomplètes.",
      rejected: "Écartée automatiquement — relance légère programmée à J+2 pour obtenir les manquants." },
    en: { name: "Anonymous enquiry", request: "\"how much does a pool cost\"",
      verdict: "Nothing actionable, incomplete contact details.",
      rejected: "Discarded automatically — light follow-up scheduled at D+2 to collect the missing details." } },
  { id: "l04", day: 3, score: 91, accepted: true, source: "recommandation",
    fr: { name: "Hôtel du Rivage · Évian", request: "Reprise d'étanchéité et filtration sur bassin recevant du public, intervention hors saison.",
      verdict: "Client professionnel, contrainte réglementaire, budget validé.",
      email: { subject: "Bassin ERP — reprise étanchéité",
        body: "Bonjour,\n\nUn bassin recevant du public impose un calendrier serré et des matériaux tracés. Nous intervenons régulièrement dans ce cadre.\n\nJe vous propose une visite technique pour établir le diagnostic d'étanchéité avant chiffrage." } },
    en: { name: "Hôtel du Rivage · Évian", request: "Waterproofing and filtration overhaul on a public pool, off-season work.",
      verdict: "Trade client, regulatory constraint, budget confirmed.",
      email: { subject: "Public pool — waterproofing overhaul",
        body: "Hello,\n\nA public pool means a tight schedule and traceable materials. We work in that context regularly.\n\nI suggest a technical visit to establish the waterproofing diagnosis before pricing." } } },
  { id: "l05", day: 5, score: 62, accepted: true, source: "telephone",
    fr: { name: "Marc D. · Douvaine", request: "Abri de piscine, hésite entre bas et mi-haut, pas de budget arrêté.",
      verdict: "Projet réel mais budget flou.",
      email: { subject: "Abri de piscine — les deux options",
        body: "Bonjour Marc,\n\nEntre un abri bas et un mi-haut, l'écart de prix va souvent du simple au double, mais l'usage n'est pas le même : le mi-haut permet de nager couvert.\n\nJe vous envoie deux configurations chiffrées pour situer les ordres de grandeur." } },
    en: { name: "Marc D. · Douvaine", request: "Pool enclosure, torn between low and mid-height, no fixed budget.",
      verdict: "Real project but vague budget.",
      email: { subject: "Pool enclosure — both options",
        body: "Hello Marc,\n\nBetween a low and a mid-height enclosure the price often doubles, but the use differs: a mid-height lets you swim under cover.\n\nI am sending two priced configurations so you can place the orders of magnitude." } } },
  { id: "l06", day: 7, score: 18, accepted: false, source: "formulaire",
    fr: { name: "Démarchage · agence web", request: "Proposition de refonte de site internet.",
      verdict: "Hors sujet.",
      rejected: "Sollicitation commerciale, pas une demande client. Écartée sans réponse." },
    en: { name: "Cold outreach · web agency", request: "Website redesign proposal.",
      verdict: "Off-topic.",
      rejected: "Sales solicitation, not a customer enquiry. Discarded without reply." } },
  { id: "l07", day: 8, score: 79, accepted: true, source: "formulaire",
    fr: { name: "Claire B. · Anthy-sur-Léman", request: "Pompe à chaleur pour allonger la saison, bassin de 45 m³.",
      verdict: "Besoin précis, volume connu, décision rapide attendue.",
      email: { subject: "Chauffage de votre bassin à Anthy",
        body: "Bonjour Claire,\n\nPour 45 m³ dans le Chablais, une PAC de 12 kW permet de tenir 28 °C d'avril à octobre.\n\nJe vous joins deux modèles, dont un silencieux si le bassin est proche des chambres." } },
    en: { name: "Claire B. · Anthy-sur-Léman", request: "Heat pump to extend the season, 45 m³ pool.",
      verdict: "Precise need, known volume, quick decision expected.",
      email: { subject: "Heating your pool in Anthy",
        body: "Hello Claire,\n\nFor 45 m³ in this area, a 12 kW heat pump will hold 28 °C from April to October.\n\nI am attaching two models, including a quiet one if the pool sits near bedrooms." } } },
  { id: "l08", day: 10, score: 45, accepted: true, source: "salon",
    fr: { name: "Pascal T. · Margencel", request: "Projet de bassin pour dans deux ans, se renseigne.",
      verdict: "Intention réelle mais échéance lointaine.",
      email: { subject: "Votre projet de bassin",
        body: "Bonjour Pascal,\n\nÀ deux ans d'échéance, le plus utile est de caler l'implantation et le budget d'ensemble : c'est ce qui bouge le moins.\n\nJe vous envoie notre guide de préparation. On refait le point quand votre calendrier se précise." } },
    en: { name: "Pascal T. · Margencel", request: "Pool project in about two years, gathering information.",
      verdict: "Genuine intent but distant deadline.",
      email: { subject: "Your pool project",
        body: "Hello Pascal,\n\nTwo years out, the most useful thing is to settle the siting and the overall budget — those move the least.\n\nI am sending our preparation guide. We can revisit when your timing firms up." } } },
  { id: "l09", day: 12, score: 84, accepted: true, source: "recommandation",
    fr: { name: "Camping du Lac · Excenevex", request: "Contrat d'entretien bi-hebdomadaire pour la saison, deux bassins.",
      verdict: "Récurrent, professionnel, volume connu.",
      email: { subject: "Contrat d'entretien saison",
        body: "Bonjour,\n\nDeux passages par semaine sur deux bassins en camping, c'est un format que nous couvrons, analyses réglementaires comprises.\n\nJe vous adresse le contrat type avec le détail des relevés fournis." } },
    en: { name: "Camping du Lac · Excenevex", request: "Twice-weekly maintenance contract for the season, two pools.",
      verdict: "Recurring, trade, known volume.",
      email: { subject: "Seasonal maintenance contract",
        body: "Hello,\n\nTwo visits a week on two campsite pools is a format we cover, regulatory testing included.\n\nI am sending the standard contract with the detail of the readings provided." } } },
  { id: "l10", day: 15, score: 27, accepted: false, source: "formulaire",
    fr: { name: "Demande hors zone · Nice", request: "Construction d'un bassin dans les Alpes-Maritimes.",
      verdict: "Hors zone d'intervention.",
      rejected: "À 600 km de la zone couverte. Réponse envoyée avec l'orientation vers un confrère régional." },
    en: { name: "Out-of-area enquiry · Nice", request: "Pool build in the Alpes-Maritimes.",
      verdict: "Outside the service area.",
      rejected: "600 km from the covered area. Reply sent pointing to a regional peer." } },
  { id: "l11", day: 18, score: 68, accepted: true, source: "formulaire",
    fr: { name: "Nathalie G. · Neuvecelle", request: "Transformation d'un bassin béton vieillissant, veut aussi chauffer.",
      verdict: "Deux lots à chiffrer, budget à cadrer.",
      email: { subject: "Rénovation et chauffage à Neuvecelle",
        body: "Bonjour Nathalie,\n\nRénovation et chauffage se traitent bien ensemble : la reprise du local technique sert aux deux, ce qui évite d'y revenir.\n\nJe prépare un chiffrage en deux lots pour que vous puissiez arbitrer." } },
    en: { name: "Nathalie G. · Neuvecelle", request: "Converting an ageing concrete pool, also wants heating.",
      verdict: "Two work packages to price, budget to frame.",
      email: { subject: "Renovation and heating in Neuvecelle",
        body: "Hello Nathalie,\n\nRenovation and heating work well together: reworking the plant room serves both, which saves going back twice.\n\nI am preparing pricing in two packages so you can arbitrate." } } },
  { id: "l12", day: 21, score: 55, accepted: true, source: "telephone",
    fr: { name: "Olivier F. · Marin", request: "Abri haut adossé à la maison, veut une terrasse mobile en plus.",
      verdict: "Projet ambitieux, faisabilité à vérifier.",
      email: { subject: "Abri adossé et terrasse mobile",
        body: "Bonjour Olivier,\n\nUn abri adossé demande de vérifier la reprise en façade, et une terrasse mobile impose une profondeur constante. Les deux sont possibles, mais pas sur toutes les configurations.\n\nUne visite technique permettra de trancher avant de chiffrer." } },
    en: { name: "Olivier F. · Marin", request: "High lean-to enclosure against the house, plus a moving floor.",
      verdict: "Ambitious project, feasibility to confirm.",
      email: { subject: "Lean-to enclosure and moving floor",
        body: "Hello Olivier,\n\nA lean-to enclosure means checking the wall fixing, and a moving floor requires constant depth. Both are possible, but not in every configuration.\n\nA technical visit will settle it before we price." } } },
  { id: "l13", day: 24, score: 22, accepted: false, source: "formulaire",
    fr: { name: "Demande incomplète", request: "« rappelez-moi »",
      verdict: "Message sans contenu.",
      rejected: "Aucun numéro renseigné, aucun objet. Relance automatique envoyée, restée sans réponse." },
    en: { name: "Incomplete enquiry", request: "\"call me back\"",
      verdict: "Message with no content.",
      rejected: "No number given, no subject. Automatic follow-up sent, no reply." } },
  { id: "l14", day: 27, score: 71, accepted: true, source: "formulaire",
    fr: { name: "Résidence Beauregard · Publier", request: "Reprise de plage et garde-corps aux normes pour une copropriété.",
      verdict: "Contrainte normative, décision collective à prévoir.",
      email: { subject: "Mise aux normes de la plage",
        body: "Bonjour,\n\nPour une copropriété, nous fournissons un dossier chiffré présentable en assemblée générale, avec le détail des obligations de sécurité.\n\nJe vous propose une visite pour relever l'existant." } },
    en: { name: "Beauregard residence · Publier", request: "Deck rework and compliant guardrails for a residents' association.",
      verdict: "Compliance constraint, collective decision expected.",
      email: { subject: "Bringing the deck up to standard",
        body: "Hello,\n\nFor a residents' association we provide a priced pack suitable for a general meeting, with the safety obligations set out.\n\nI suggest a visit to survey the existing installation." } } },
  { id: "l15", day: 29, score: 38, accepted: false, source: "formulaire",
    fr: { name: "Étudiant · mémoire", request: "Questionnaire pour un travail universitaire sur la filière piscine.",
      verdict: "Pas une demande commerciale.",
      rejected: "Demande documentaire. Réponse courtoise envoyée avec les liens publics, sans passage en commercial." },
    en: { name: "Student · dissertation", request: "Questionnaire for a university project on the pool industry.",
      verdict: "Not a commercial enquiry.",
      rejected: "Research request. Polite reply sent with public links, no salesperson involved." } },
  { id: "l16", day: 41, score: 81, accepted: true, source: "recommandation",
    fr: { name: "Bruno O. · Yvoire", request: "Bassin béton 10×5 avec local enterré, recommandé par un ancien client.",
      verdict: "Recommandation, budget confirmé, projet daté.",
      email: { subject: "Votre projet à Yvoire",
        body: "Bonjour Bruno,\n\nMerci — les projets qui arrivent par recommandation partent toujours plus vite, on connaît déjà le niveau d'exigence attendu.\n\nPour un 10×5 avec local enterré, la contrainte principale sera l'accès engins. Je passe voir le terrain." } },
    en: { name: "Bruno O. · Yvoire", request: "10×5 concrete pool with buried plant room, referred by a past client.",
      verdict: "Referral, confirmed budget, dated project.",
      email: { subject: "Your project in Yvoire",
        body: "Hello Bruno,\n\nThank you — referred projects always move faster, we already know the standard expected.\n\nFor a 10×5 with a buried plant room, machine access will be the main constraint. I will come and see the plot." } } },
  { id: "l17", day: 55, score: 49, accepted: true, source: "salon",
    fr: { name: "Sandrine W. · Marin", request: "Liner armé et projecteurs, compare trois installateurs.",
      verdict: "Mise en concurrence assumée.",
      email: { subject: "Liner armé — notre proposition",
        body: "Bonjour Sandrine,\n\nVous comparez, c'est normal. Ce qui distingue les devis sur ce poste, c'est l'épaisseur du liner et la garantie de pose : les deux figurent en clair sur le nôtre.\n\nJe reste disponible pour comparer ligne à ligne." } },
    en: { name: "Sandrine W. · Marin", request: "Reinforced liner and lights, comparing three installers.",
      verdict: "Openly shopping around.",
      email: { subject: "Reinforced liner — our proposal",
        body: "Hello Sandrine,\n\nYou are comparing, which is fair. What sets quotes apart on this job is liner thickness and the installation warranty — both are spelled out on ours.\n\nHappy to go through it line by line." } } },
  { id: "l18", day: 73, score: 66, accepted: true, source: "formulaire",
    fr: { name: "Hôtel des Cygnes · Thonon-les-Bains", request: "Rénovation complète d'un bassin intérieur, fermeture prévue en janvier.",
      verdict: "Fenêtre d'intervention contrainte mais planifiée.",
      email: { subject: "Bassin intérieur — fenêtre de janvier",
        body: "Bonjour,\n\nUne fermeture en janvier est la bonne fenêtre : c'est aussi la nôtre, hors saison. Sur un bassin intérieur, le point critique reste la ventilation, souvent sous-dimensionnée après rénovation.\n\nJe vous propose une visite avec notre technicien traitement d'air." } },
    en: { name: "Hôtel des Cygnes · Thonon-les-Bains", request: "Full renovation of an indoor pool, closure planned for January.",
      verdict: "Constrained but planned work window.",
      email: { subject: "Indoor pool — the January window",
        body: "Hello,\n\nA January closure is the right window — it is ours too, off season. On an indoor pool the critical point remains ventilation, often undersized after a renovation.\n\nI suggest a visit with our air-handling technician." } } },
];

const invoices: Invoice[] = [
  { id: "i01", day: 3,  dueIn: 27, amount: 4300,  vatRate: 0.2, paid: false, category: "entretien",
    fr: { ref: "F-2026-0412", client: "Copropriété Les Tilleuls" }, en: { ref: "INV-2026-0412", client: "Les Tilleuls residence" } },
  { id: "i02", day: 5,  dueIn: 25, amount: 6800,  vatRate: 0.2, paid: true,  category: "equipement",
    fr: { ref: "F-2026-0411", client: "M. L. · Anthy" }, en: { ref: "INV-2026-0411", client: "Mr L. · Anthy" } },
  { id: "i03", day: 9,  dueIn: 21, amount: 2900,  vatRate: 0.2, paid: true,  category: "entretien",
    fr: { ref: "F-2026-0409", client: "Mme P. · Douvaine" }, en: { ref: "INV-2026-0409", client: "Ms P. · Douvaine" } },
  { id: "i04", day: 12, dueIn: 18, amount: 3600,  vatRate: 0.2, paid: false, category: "entretien",
    fr: { ref: "F-2026-0407", client: "Camping du Lac" }, en: { ref: "INV-2026-0407", client: "Camping du Lac" } },
  { id: "i05", day: 16, dueIn: 14, amount: 12100, vatRate: 0.1, paid: true,  category: "renovation",
    fr: { ref: "F-2026-0404", client: "M. J. · Thonon" }, en: { ref: "INV-2026-0404", client: "Mr J. · Thonon" } },
  { id: "i06", day: 21, dueIn: 9,  amount: 5600,  vatRate: 0.2, paid: true,  category: "equipement",
    fr: { ref: "F-2026-0401", client: "Mme B. · Anthy" }, en: { ref: "INV-2026-0401", client: "Ms B. · Anthy" } },
  { id: "i07", day: 24, dueIn: 6,  amount: 8900,  vatRate: 0.1, paid: false, category: "renovation",
    fr: { ref: "F-2026-0398", client: "Mme W. · Marin" }, en: { ref: "INV-2026-0398", client: "Ms W. · Marin" } },
  { id: "i08", day: 28, dueIn: -2, amount: 7900,  vatRate: 0.2, paid: false, category: "abri",
    fr: { ref: "F-2026-0395", client: "M. E. · Perrignier" }, en: { ref: "INV-2026-0395", client: "Mr E. · Perrignier" } },
  { id: "i09", day: 33, dueIn: -7, amount: 3400,  vatRate: 0.2, paid: false, category: "entretien",
    fr: { ref: "F-2026-0391", client: "M. R. · Lugrin" }, en: { ref: "INV-2026-0391", client: "Mr R. · Lugrin" } },
  { id: "i10", day: 40, dueIn: 20, amount: 24100, vatRate: 0.1, paid: true,  category: "construction",
    fr: { ref: "F-2026-0384", client: "M. et Mme K. · Évian" }, en: { ref: "INV-2026-0384", client: "Mr & Mrs K. · Évian" } },
  { id: "i11", day: 49, dueIn: 11, amount: 13900, vatRate: 0.1, paid: true,  category: "renovation",
    fr: { ref: "F-2026-0377", client: "Mme W. · Marin" }, en: { ref: "INV-2026-0377", client: "Ms W. · Marin" } },
  { id: "i12", day: 57, dueIn: 3,  amount: 16600, vatRate: 0.1, paid: true,  category: "construction",
    fr: { ref: "F-2026-0369", client: "M. O. · Yvoire" }, en: { ref: "INV-2026-0369", client: "Mr O. · Yvoire" } },
  { id: "i13", day: 66, dueIn: -6, amount: 4600,  vatRate: 0.2, paid: false, category: "entretien",
    fr: { ref: "F-2026-0358", client: "Camping du Lac" }, en: { ref: "INV-2026-0358", client: "Camping du Lac" } },
  { id: "i14", day: 74, dueIn: 16, amount: 9300,  vatRate: 0.1, paid: true,  category: "renovation",
    fr: { ref: "F-2026-0350", client: "Hôtel des Cygnes" }, en: { ref: "INV-2026-0350", client: "Hôtel des Cygnes" } },
];

export const PISCINISTE_DATA: SectorData = {
  company: "Piscines Bleu Léman",
  quotes,
  calls,
  leads,
  invoices,
  categories: [
    { key: "construction", fr: "Construction", en: "New build" },
    { key: "renovation", fr: "Rénovation", en: "Renovation" },
    { key: "abri", fr: "Abris et couvertures", en: "Enclosures & covers" },
    { key: "entretien", fr: "Entretien", en: "Maintenance" },
    { key: "equipement", fr: "Équipement", en: "Equipment" },
  ],
  sources: [
    { key: "formulaire", fr: "Formulaire du site", en: "Website form" },
    { key: "telephone", fr: "Appel entrant", en: "Inbound call" },
    { key: "recommandation", fr: "Recommandation", en: "Referral" },
    { key: "salon", fr: "Salon", en: "Trade show" },
  ],
};
